(* ::Package:: *)

(* Autogenerated Package *)

$IDESettingsPath::usage="The path to look for settings on";


Begin["`Private`"];


(* ::Subsection:: *)
(*Settings*)



$IDESettingsPath=
  {
    FileNameJoin@{$UserBaseDirectory, $PackageName, "Settings"},
    PackageFilePath["Resources", "Settings"]
    };


End[];



