(* ::Package:: *)

(* Autogenerated Package *)

GitHubCheck::usage=
  "Checks the results coming out of GitHub";


Begin["`Private`"];


(* ::Subsubsection::Closed:: *)
(*Common Messages*)



Ems::noauth=
  "Ems requires authentication with GitHub";
Ems::nohub=
  "Ems can't connect to github.com. \
Are you connected to the internet?";
Ems::badreq=
  "Request to GitHub failed with message: \"``\"
Contact b3m2a1@gmail.com for details.";
Ems::badcon=
  "Request couldn't be completed due to a conflict with message: \"``\"
Contact b3m2a1@gmail.com for details.";
Ems::badend=
  "Request couldn't be completed due to missing endpoint with message: \"``\"
Contact b3m2a1@gmail.com for details.";
Ems::badhub=
  "Internal error, request to GitHub failed.
Contact b3m2a1@gmail.com for details.";


(* ::Subsubsection::Closed:: *)
(*PPSGitHubCheck*)



GitHubCheck[res_]:=
  Which[
    Head[res]===GitHub,
      Message[Ems::badhub];
      $Failed,
    !AssociationQ@res,
      res;
      Message[Ems::nohub];
      $Failed,
    res["StatusCode"]===401,
      Message[Ems::noauth];
      $Failed,
    res["StatusCode"]===404,
      Message[Ems::badend, res["Message"]];
      $Failed,
    res["StatusCode"]===409,
      Message[Ems::badcon, res["Message"]];
      $Failed,
    res["StatusCode"]>400,
      Message[Ems::badreq, StringReplace[res["Message"], "\n"->" "]];
      $Failed,
    True,
      res["Content"]
    ]
      


End[];



