(* ::Package:: *)

(* Autogenerated Package *)

(* ::Section:: *)
(*SimpleDocs*)



(* ::Text:: *)
(*
	This implements the code behind the SimpleDocs stylesheet and palette
*)



(* ::Subsubsection::Closed:: *)
(*Core Stuff*)



$NotebookTemplates::usage="";


(* ::Subsubsection::Closed:: *)
(*Project Stuff*)



DocsProjectsDirectory::usage="";
SetDocsProjectsDirectory::usage="";
$DocsProjectPath::usage="";
ListDocsProjects::usage="";
ListProjectNotebooks::usage="";
ListProjectSymbolPages::usage="";
ListProjectGuidePages::usage="";
ListProjectTutorialPages::usage="";


DocsProjects::usage="";
RemoveProject::usage="";
LoadProjectConfig::usage="";
ReloadProjectConfig::usage="";
EnsureLoadProject::usage="";


FindProjectConfig::usage="";
OpenProjectConfig::usage="";
SetProjectOptions::usage="";
InitializeDocsProject::usage="";


ProjectSaveDirectory::usage="";
SiteSaveDirectory::usage="";
DocsSaveDirectory::usage="";


(* ::Subsubsection::Closed:: *)
(*Notebooks*)



SetNotebookPaclet::usage="deprecated";
SetNotebookProject::usage="";
SaveNotebookToDocumentation::usage="";
SaveNotebookToPaclet::usage="deprecated";
SaveNotebookMarkdown::usage="";
SaveNotebookToProject::usage=""
SaveNotebookToPacletProject::usage="deprecated";
CheckSaveNotebook::usage="";


CreateTemplateNotebook::usage="";
SampleTemplateNotebook::usage="";


(* ::Subsubsection::Closed:: *)
(*GUI Elements*)



$InsertionMenu::usage="";
$HamburgerMenu::usage="";
$MetadataEditor::usage="";
$DockedCell::usage="";


(* ::Subsubsection::Closed:: *)
(*Docs*)



InitializeDocsSite::usage="";
BuildDocsSite::usage="";
BuildNotebookDocsSite::usage="";
OpenDocsSiteConfig::usage="";
OpenLocalDocsSite::usage="";


(* ::Subsubsection::Closed:: *)
(*Paclets*)



SetPacletInfo::usage="";
CreateDocumentationPaclet::usage="";
BundlePaclet::usage="";


(* ::Subsubsection::Closed:: *)
(*Workbench Convert*)



WorkbenchTemplateData::usage=
  "Pulls data from the Workbench templates";
FromWorkbenchTemplate::usage=
  "Extracts Workbench template data and rebuilds as a SimpleDocs notebook";


Begin["`Private`"];


(* ::Subsection:: *)
(*Projects*)



(* ::Text:: *)
(*
	Need to allow systems to customize their shiz. Might make sense to set up some kind of \[OpenCurlyDoubleQuote]project\[CloseCurlyDoubleQuote] system where that project can be a paclet or it can be standalone...
	This is a little messy right now, but the idea is to have a listing of \[OpenCurlyDoubleQuote]projects\[CloseCurlyDoubleQuote] that are currently being worked on. Each \[OpenCurlyDoubleQuote]project\[CloseCurlyDoubleQuote] has two core components, a project root directory and a config file. Neither is strictly necessary, but each is useful.
	Then all project property lookups can be done against the $DocsProject symbol allowing for centralization of options. This also can allow for batch building and things since we have a root directory.
	The other options I\[CloseCurlyQuote]m thinking will go here are:
		- Metadata: base metadata for all notebooks, when set metadata or whatever is clicked it\[CloseCurlyQuote]ll autofill any automatic values with values taken from here
		- BuildDirectory: a directory for building to outside of the default places. Might need two of these, one for the site, one for the basic documentation pages
		- MarkdownOptions: options to be sent to the Markdown converter so that they don\[CloseCurlyQuote]t have to be written into literally every page
	Each notebook will store what its parent project is (will need to implement some nice guessing/handling cloning notebooks of old ones so people do go insane doing this all the time). This will be Ensure loaded so that all the necessary properties exist to pull from.
*)



(* ::Subsubsection::Closed:: *)
(*DocsProjectsDirectory*)



DocsProjectsDirectory[]:=
  If[!StringQ[$DocsProjectsDirectory]||!DirectoryQ[$DocsProjectsDirectory], 
    $DocsProjectsDirectory=
      FileNameJoin@{$UserBaseDirectory, "ApplicationData", "SimpleDocs"},
    $DocsProjectsDirectory
    ]
SetDocsProjectsDirectory[dir_]:=
  (
    $DocsProjectsDirectory=dir;
    DocsProjectsDirectory[]
    )


$DocsProjectPath=
  {
    };


(* ::Subsubsection::Closed:: *)
(*ListProjects*)



ListDocsProjects//Clear
ListDocsProjects[pattern_:"*"]:=
  Select[DirectoryQ]@
    FileNames[pattern, Prepend[$DocsProjectPath, DocsProjectsDirectory[]]]


(* ::Subsubsection::Closed:: *)
(*ListProjectNotebooks*)



ListDocsProjectNotebooks//Clear
ListDocsProjectNotebooks[projName_String, type_]:=
  FileNames[
    "*.nb",
    getProjectSaveLocation[
      If[DirectoryQ[projName], 
        EnsureLoadProject[projName][[1]],
        projName
        ], 
      type
      ],
    2
    ];
ListProjectSymbolPages[projName_]:=
  ListDocsProjectNotebooks[projName, "Symbol"]
ListProjectGuidePages[projName_]:=
  ListDocsProjectNotebooks[projName, "Guide"]
ListProjectTutorialPages[projName_]:=
  ListDocsProjectNotebooks[projName, "Tutorial"]


(* ::Subsubsection::Closed:: *)
(*$DocsProjects*)



If[!AssociationQ@$DocsProjects, $DocsProjects=<||>];


DocsProjects[]:=
  $DocsProjects;
DocsProjects[name_String]:=
  $DocsProjects[name];
DocsProjects[fn_]:=
  KeySelect[$DocsProjects, fn];


SetProjectOptions[name_, opts_]:=
  If[KeyExistsQ[$DocsProjects, name],
    AssociateTo[$DocsProjects[name], opts]
    ];


RemoveProject[name_]:=
  KeyDropFrom[$DocsProjects, name];


(* ::Subsubsection::Closed:: *)
(*getFileProject*)



possibleHeadPaths=
  {
    {"project", "docs", __},
    {"docs", _},
    {"docs"},
    {"Documentation", __}
    };


getFileProject[file_String]:=
  Module[
    {
      fsplit=FileNameSplit[file],
      split
      },
    split=
      Replace[
        fsplit,
        Append[
          Map[Join[{head__}, #, {tail_}]:>{head}&, possibleHeadPaths],
          _->None
          ]
        ];
    If[split===Null,
      DirectoryName@file,
      FileNameJoin@split
      ]
    ]
    


(* ::Subsubsection::Closed:: *)
(*getFEFileDir*)



$standardPathStarters=
  Thread@Hold@
    {
      System`$TemporaryDirectory,
      PacletManager`$UserBasePacletsDirectory,System`$CacheBaseDirectory,
      System`$UserBaseDirectory,System`$LaunchDirectory,
      System`$UserDocumentsDirectory,System`$TopDirectory,
      System`$InstallationDirectory,PacletManager`$BasePacletsDirectory,
      System`$HomeDirectory, System`$BaseDirectory,
      System`$RootDirectory
      };


makeFEFile[path_, starter_]:=
  Module[
    {
      split
      },
    split=
      DeleteCases[""]@
        If[starter===None,
          FileNameSplit[path],
          FileNameSplit[StringTrim[path, ReleaseHold@starter]]
          ];
    Which[
      starter===None&&Length@split==1,
        FrontEnd`FileName[{}, Evaluate@split[[1]]],
      starter===None,
        FrontEnd`FileName[Evaluate@split[[;;-2]], Evaluate@split[[-1]]],
      True,
        FrontEnd`FileName[
          Evaluate@
            Prepend[
              split[[;;-2]],
              starter
              ],
          Evaluate@split[[-1]]
          ]/.Hold[s_]:>s
      ]
    ]


getFEFile[dirName_String]:=
  Module[{starter, expDir=ExpandFileName@dirName},
    starter=
      SelectFirst[$standardPathStarters,
        StringStartsQ[expDir, ReleaseHold@#]&,
        None
        ];
    makeFEFile[expDir, starter]
    ];
getFEFile[e_]:=
  None;


(* ::Subsubsection::Closed:: *)
(*getCleanFName*)



getCleanFName//Clear;
getCleanFName[FrontEnd`FileName[args__]]:=
  ToFileName[FileName[args]];
getCleanFName[l:{__String}]:=
  FileNameJoin@l
getCleanFName[s_String?(StringLength[#]>0&)]:=s;
getCleanFName[e_]:=None;


(* ::Subsubsection::Closed:: *)
(*findDirConfigFile*)



$defaultConfigPaths=
  {
    {"project", "docs", "config"},
    {"Config", "SimpleDocs", "Config"},
    {"SimpleDocsConfig"},
    {"config"}
    };
findDirConfigFile[dir_]:=
  SelectFirst[
    Join[
      FileNameJoin@Prepend[#, dir]<>".wl"&/@
        $defaultConfigPaths,
      FileNameJoin@Prepend[#, dir]<>".m"&/@
        $defaultConfigPaths
      ],
    FileExistsQ,
    None
    ]


(* ::Subsubsection::Closed:: *)
(*LoadProjectConfig*)



(*LoadProjectConfig[name, dir, config]~PackageAddUsage~
	"loads a project named name in directory dir with config file config";*)
LoadProjectConfig//Clear
LoadProjectConfig[projBase_String, projDir_String, configFile_String]:=
  Module[
    {
      feFileDir,
      projName,
      trueDir,
      trueConfig,
      props
      },
    trueDir=getCleanFName@projDir;
    trueConfig=getCleanFName@configFile;
    If[!TrueQ@Quiet@FileExistsQ@trueConfig,
      trueConfig=FileNameJoin@{trueDir, trueConfig}
      ];
    props=
      Association@
        Replace[Quiet@Get[trueConfig], Except[_?OptionQ|_Association]-><||>];
    projName=Lookup[props, "Name", projBase];
    feFileDir=getFEFile[trueDir];
    If[!KeyExistsQ[props, "Directory"],
      If[StringQ[trueDir]&&DirectoryQ@trueDir,
        props["Directory"]=feFileDir,
        props["Directory"]=None
        ]
      ];
    If[!KeyExistsQ[props, "ConfigFile"],
      If[StringQ[trueConfig]&&StringLength[trueConfig]>0&&FileExistsQ[trueConfig], 
        props["ConfigFile"]=
          With[{ec=ExpandFileName@trueConfig, ed=getCleanFName[feFileDir]},
            makeFEFile[
              StringTrim[ec, ed],
              None
              ]
            ];,
        props["ConfigFile"]=None
        ]
      ];
    $DocsProjects[projName]=props;
    projName
    ];
LoadProjectConfig[projName_String, projDir_, configFile_]:=
  LoadProjectConfig[projName, 
    If[!StringQ@projDir, "", projDir], 
    If[!StringQ@configFile, "", configFile]
    ];


(*LoadProjectConfig[dir]~PackageAddUsage~
	"loads a project a directory dir with automatic config file and name";*)
LoadProjectConfig[dir_String?DirectoryQ]:=
  LoadProjectConfig[
    cleanProjectBaseName@dir, 
    dir,
    findDirConfigFile[dir]
    ];


(*LoadProjectConfig[pac]~PackageAddUsage~
	"loads the project in paclet pac";*)
LoadProjectConfig[pac_PacletManager`Paclet]:=
  LoadProjectConfig[
    cleanProjectBaseName@pac["Name"],
    pac["Location"],
    findDirConfigFile@pac["Location"]
    ];
LoadProjectConfig[s_String?(Length[ListDocsProjects[#]]>0&)]:=
  LoadProjectConfig[ListDocsProjects[s][[1]]];
LoadProjectConfig[s_String?(Length[PacletManager`PacletFind[#]]>0&)]:=
  LoadProjectConfig@PacletManager`PacletFind[s][[1]];


(* ::Subsubsection::Closed:: *)
(*ReloadProjectConfig*)



ReloadProjectConfig[proj_]:=
  $DocsProjects[proj]=
    Merge[
      {
        $DocsProjects[proj],
        Association@
          Replace[
            Quiet@Get[getProjectConfFilePath[proj]], 
            Except[_?OptionQ|_Association]-><||>
            ]
        },
      Last
      ];


(* ::Subsubsection::Closed:: *)
(*cleanProjectBaseName*)



cleanProjectBaseName[name_]:=
  StringSplit[FileBaseName@name, "-"][[1]]


(* ::Subsubsection::Closed:: *)
(*projectQ*)



projectQ//Clear
projectQ[projName_String]:=
  KeyExistsQ[$DocsProjects, projName]||
    (DirectoryQ[projName]&&KeyExistsQ[$DocsProjects, cleanProjectBaseName@projName]);
projectQ[___]:=False


(* ::Subsubsection::Closed:: *)
(*get stuff*)



(* ::Subsubsubsection::Closed:: *)
(*getProjectName*)



getProjectName[name_]:=
  Which[
    KeyExistsQ[$DocsProjects, name], 
      name,
    KeyExistsQ[$DocsProjects, cleanProjectBaseName@name],
      FileBaseName@name,
    True,
      None
    ]


(* ::Subsubsubsection::Closed:: *)
(*getProjectProp*)



getProjectProp[pname_, prop_, default_]:=
  Lookup[
    Lookup[$DocsProjects, pname, <||>],
    prop,
    default
    ]


(* ::Subsubsubsection::Closed:: *)
(*getProjectConfFile*)



getProjectConfFile[pname_]:=
  getProjectProp[pname, "ConfigFile", None]


(* ::Subsubsubsection::Closed:: *)
(*getProjectConfFilePath*)



getProjectConfFilePath[pname_]:=
  Module[
    {
      cf=getProjectConfFile[pname],
      dir=getProjectDir[pname]
      },
    If[cf=!=None,
      cf=getCleanFName[cf];
      If[ExpandFileName[cf]!=cf&&dir=!=None,
        cf=FileNameJoin@{getCleanFName@dir, cf}
        ];
      ];
    cf
    ]


(* ::Subsubsubsection::Closed:: *)
(*getProjectDir*)



getProjectDir[pname_]:=
  getProjectProp[pname, "Directory", None]


(* ::Subsubsubsection::Closed:: *)
(*getProjectLayout*)



getProjectLayout//Clear
getProjectLayout[bdir_, bconf_]:=
  Module[
    {
      dir=bdir,
      conf=bconf
      },
    If[MatchQ[dir, _FrontEnd`FileName],
      dir=getCleanFName@dir
      ];
    If[MatchQ[conf, _FrontEnd`FileName],
      conf=getCleanFName@conf
      ];
    If[StringQ@conf&&!(ExpandFileName[conf]==conf)&&StringQ@dir,
      conf=FileNameJoin@{dir, conf}
      ];
    {dir, conf}
    ];
getProjectLayout[pname_String]:=
  Prepend[pname]@
    getProjectLayout[getProjectDir[pname], getProjectConfFile[pname]];
getProjectLayout[nb_NotebookObject]:=
  getProjectLayout@getNBProject[nb];
getProjectLayout[___]:=
  {None, None, None}


(* ::Subsubsubsection::Closed:: *)
(*getProjectPaclet*)



getProjectPaclet[pname_]:=
  Module[
    {
      pacName,
      dir
      },
    pacName=getProjectProp[pname, "Paclet", None];
    If[pacName===None,
      dir=getProjectDir@pname;
      If[PacletExecute["ValidDirectoryQ", dir], 
        PacletExecute["Paclet", dir],
        None
        ],
      PacletManager`PacletFind[pacName]
      ]
    ]


(* ::Subsubsubsection::Closed:: *)
(*getProjectPacletInfo*)



getProjectPacletInfo[pname_]:=
  Module[
    {
      pacName,
      dir
      },
    pacName=getProjectProp[pname, "Paclet", None];
    If[pacName===None,
      dir=getProjectDir@pname;
      If[PacletExecute["ValidDirectoryQ", dir], 
        PacletExecute["Association", dir],
        None
        ],
      PacletManager`PacletInformation[pacName]
      ]
    ]


(* ::Subsubsubsection::Closed:: *)
(*getProjectContext*)



getProjectContext[pname_]:=
  Module[
    {
      cont,
      pac,
      pi
      },
    cont=
      Lookup[
        getProjectProp[pname, "Metadata", {}],
        "context",
        None
        ];
    If[!StringQ@cont,
      pi=getProjectPacletInfo[pname];
      cont=First["Context"/.Append[pi, "Context"->{Lookup[pi, "Name"]<>"`"}]]
      ];
    cont
    ]


(* ::Subsubsubsection::Closed:: *)
(*getProjectBuildDir*)



getProjectBuildDir[pname_]:=
  Module[
    {
      bd=getCleanFName@getProjectProp[pname, "BuildDirectory", Automatic]
      },
    If[StringQ@bd,
      If[ExpandFileName[bd]!=bd,
        bd=FileNameJoin@{getCleanFName@getProjectDir@pname, bd}
        ],
      bd=getCleanFName@getProjectDir@pname
      ];
    bd  
    ]


(* ::Subsubsubsection::Closed:: *)
(*getProjectSitePath*)



$projectSitePathDefault={"project", "docs"};


getProjectSitePath[pname_]:=
  getProjectProp[pname, "SitePath", $projectSitePathDefault]


(* ::Subsubsubsection::Closed:: *)
(*getProjectSiteBuildPath*)



(* ::Text:: *)
(*
	This might need an update some day, but should work for now
*)



getProjectSiteBuildPath[proj_]:=
  FileNameJoin@{getProjectSitePath[proj], "output"};


(* ::Subsubsection::Closed:: *)
(*OpenProjectConfig*)



$defaultConfigOptions=
  {
    "BuildDirectory"->Automatic,
    "MarkdownOptions"->{}
    }


FindProjectConfig[projName_]:=
  Module[
    {
      cf=getProjectConfFile[projName],
      dir
      },
    If[!(StringQ[cf]&&FileExistsQ[cf])&&DirectoryQ[projName],
      cf=findDirConfigFile[projName]
      ];
    If[!(StringQ[cf]&&FileExistsQ[cf]),
      dir=getCleanFName@getProjectDir[projName];
      cf=findDirConfigFile[dir];
      If[!(StringQ[cf]&&FileExistsQ[cf]),
        cf=FileNameJoin@Prepend[First@$defaultConfigPaths, dir]<>".wl";
        CreateFile[cf, CreateIntermediateDirectories->True];
        Export[cf, PrettyString[$defaultConfigOptions], "Text"]
        ]
      ];
    cf
    ]


OpenProjectConfig[projName_]:=
  SystemOpen@
    FindProjectConfig[projName];


(* ::Subsubsection::Closed:: *)
(*EnsureLoadProject*)



(* ::Text:: *)
(*
	This is stupidly messy. All I want is to be able to handle whatever combination of things we\[CloseCurlyQuote]re passed from a project name, a project directory, paclet name, config file, etc.
*)



EnsureLoadProject//Clear
EnsureLoadProject[projName_, projDir_, projConf_]:=
  Module[{pname=$Failed, pdir, pcnf},
    If[!projectQ[projName],
      Which[
        !StringQ@projName,
          pname=LoadProjectConfig[projDir],
        (!StringQ@projDir||StringLength[projDir]==0)&&
          (!StringQ@projConf||StringLength[projConf]==0),
          pname=LoadProjectConfig[projName],
        !StringQ@projConf||StringLength[projConf]==0,
          pname=LoadProjectConfig[projName, projDir, None],
        True,
          pname=LoadProjectConfig[projName, projDir, projConf]
        ],
      pname=getProjectName[projName]
      ];
    {pname, getProjectDir[pname], getProjectConfFile[pname]}
    ];
EnsureLoadProject[projName_String, projDir_String?DirectoryQ]:=
  EnsureLoadProject[
    projName,
    projDir,
    findDirConfigFile[projDir]
    ];
EnsureLoadProject[projDir_String]:=
  EnsureLoadProject[None, projDir, None];
EnsureLoadProject[nb_NotebookObject]:=
  EnsureLoadProject[
    getNbData[nb, $projNameTag],
    getNbData[nb, $projDirTag],
    getNbData[nb, $projConfigTag]
    ]


(* ::Subsubsection::Closed:: *)
(*InitializeDocsProject*)



InitializeDocsProject[rootDir_, projName_, config_:None]:=
  Module[
    {
      dir,
      cf=If[StringQ[config]&&StringLength[StringTrim@config]==0, None, config]
      },
    dir=FileNameJoin@{rootDir, projName};
    If[!DirectoryQ@dir,
      CreateDirectory[dir, CreateIntermediateDirectories->True]
      ];
    If[!(StringQ[cf]&&FileExistsQ[cf]),
      cf=findDirConfigFile[dir]
      ];
    If[!(StringQ[cf]&&FileExistsQ[cf]),
      cf=FileNameJoin@Prepend[First@$defaultConfigPaths, dir]<>".wl";
      CreateFile[cf, CreateIntermediateDirectories->True];
      Export[cf, PrettyString[$defaultConfigOptions], "Text"];
      ];
    LoadProjectConfig[
      projName, 
      dir, 
      cf
      ];
    Block[{docsSiteLoc=docsProjLoc},
      InitializeDocsSite[projName]
      ];
    dir
    ];
InitializeDocsProject[rootDir_String?DirectoryQ]:=
  InitializeDocsProject[DirectoryName[rootDir], FileBaseName@rootDir];


(* ::Subsection:: *)
(*Site*)



(* ::Subsubsection::Closed:: *)
(*docsSiteLoc*)



(* ::Subsubsubsection::Closed:: *)
(*Older*)



docsSiteLoc1//Clear
docsSiteLoc1[loc_String?(StringQ[#]&&StringLength[#]>0&&DirectoryQ[#]&)]:=
  FileNameJoin@{loc, "project", "docs"};
docsSiteLoc1[p_PacletManager`Paclet]:=
  docsSiteLoc1[p["Location"]];
docsSiteLoc1[s_String]:=
  Replace[PacletManager`PacletFind[s], {p_, ___}:>docsSiteLoc1[p]];


(* ::Subsubsubsection::Closed:: *)
(*Newer*)



docsSiteLoc[projName_]:=
  FileNameJoin@Flatten@{
    getProjectBuildDir@projName, 
    getProjectSitePath@projName
    }


(* ::Subsubsection::Closed:: *)
(*docsProjLoc*)



docsProjLoc[projName_]:=
  FileNameJoin@Flatten@{
    getCleanFName@getProjectDir@projName,
    $projectSitePathDefault
    }


(* ::Subsubsection::Closed:: *)
(*InitializeDocsSite*)



InitializeDocsSite[proj_]:=
  Module[{l=docsSiteLoc[proj], tmp},
    If[StringQ@l&&!DirectoryQ@FileNameJoin@{l, "content"},
      If[DirectoryQ[l],
        tmp=CreateArchive[l, CreateDirectory[]<>".zip"]
        ];
      Internal`WithLocalSettings[
        If[StringQ@tmp, DeleteDirectory[l, DeleteContents->True]],
        With[{s=Ems["New", l, "docs"]},
          DeleteFile/@FileNames["*", FileNameJoin@{s, "content", "ref"}];
          DeleteFile/@FileNames["*", FileNameJoin@{s, "content", "guide"}];
          s
          ],
        If[StringQ@tmp, ExtractArchive[tmp, DirectoryName@l]]
        ],
      $Failed
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*BuildDocsSite*)



BuildDocsSite[loc_, ops___]:=
  Ems["Build", docsSiteLoc[loc], ops];


(* ::Subsubsection::Closed:: *)
(*BuildNotebookDocsSite*)



(* ::Subsubsubsection::Closed:: *)
(*BuildNotebookDocsSite*)



BuildNotebookDocsSite[nb_, ploc_:Automatic]:=
  With[{proj=getNBProjectName[nb, ploc]},
    If[proj=!=None,
      buildNotebookDocsSite[proj]
      ]
    ]


(* ::Subsubsubsection::Closed:: *)
(*overrideMonitor*)



overrideMonitor//Clear


overrideMonitor[expr_, sym_]:=
  Block[{Monitor},
    SetAttributes[Monitor, HoldAllComplete];
    Monitor[a_, b_, ___]:=
      (
        sym=b;
        a
        );
    expr;
    ];
overrideMonitor~SetAttributes~HoldAll;


(* ::Subsubsubsection::Closed:: *)
(*buildNotebookDocsSite*)



$protector=False;


buildNotebookDocsSite[loc_]:=
  With[{l=docsSiteLoc[loc]},
    Block[{blech},
      If[DirectoryQ@l,
        Module[{nb},
          nb=
            MessageDialog[
              Column@{
                StringForm[
                  "Creating site @ ``", l
                  ],
                Panel[
                  Dynamic[
                    If[MatchQ[blech, _Symbol], "", blech],
                    TrackedSymbols:>{blech}
                    ],
                  ImageSize->{350, 100}
                  ]
                },
              WindowTitle->"Building Site",
              WindowFloating->True
              ];
          overrideMonitor[
            PySimpleServerOpen@
              Ems["Build", l],
            blech
            ];
          NotebookClose@nb;
          ],
        $Failed
        ]
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*OpenDocsSiteConfig*)



OpenDocsSiteConfig//Clear
OpenDocsSiteConfig[nb_NotebookObject, ploc_:Automatic]:=
  OpenDocsSiteConfig@
    getNBProjectName[nb, ploc];
OpenDocsSiteConfig[proj_]:=
  SystemOpen@
    FileNameJoin@{
      docsSiteLoc@proj, 
      "SiteConfig.wl"
      };


(* ::Subsubsection::Closed:: *)
(*OpenLocalDocsSite*)



OpenLocalDocsSite//Clear
OpenLocalDocsSite[nb_NotebookObject, ploc_:Automatic]:=
  OpenLocalDocsSite@
    getNBProjectName[nb, ploc];
OpenLocalDocsSite[proj_]:=
  PySimpleServerOpen@
    FileNameJoin@{
      docsSiteLoc@proj,
      "output"
      };


(* ::Subsection:: *)
(*Misc*)



(* ::Subsubsection::Closed:: *)
(*$MetadataMap*)



$MetadataMap=
  <|
    "Basics"->
      {
        "Context","Language","Paclet",
        "Type","Label","URI",
        "Summary","Status",
        "Title","Title Modifier","Window Title"
        },
    "Location"->
      {"Keywords","Synonyms","Index"},
    "History"->{"Built","History"},
    "Advanced"->{"Table Tags","Tutorial Collection Links","Special Keywords"}
    |>;


(* ::Subsubsection::Closed:: *)
(*$NotebookTemplates*)



(* ::Subsubsubsection::Closed:: *)
(*$miscTemplates*)



$miscTemplates=
  <|
    "TitleBar"->Cell["<Context>", "TitleBar"],
    "Divider"->Cell["", "PageBreak", PageBreakBelow->False, PageBreakAbove->False],
    "Footer"->Cell["Made with SimpleDocs", "Text", "Footer"]
    |>;


(* ::Subsubsubsection::Closed:: *)
(*$baseTemplates*)



$baseTemplates=
  <|
    "Usage"->
      Cell@
        CellGroupData[
          {
            Cell[BoxData@RowBox[{"<FunctionName>","[",RowBox[{"arg1", ",",  "arg2", ",",  "..."}],"]"}], "Code", "UsageInput"],
            Cell["description", "Text", "UsageText"]
            }
          ],
    "Guide Line"->
      Cell[
        TextData@{
          ButtonBox["Function1", BaseStyle->"Link",ButtonData->"paclet:Pkg/ref/Function1"], 
          " - ", 
          "description"
          }, "Text"],
    "Details"->
      Cell@
        CellGroupData[
          {
            Cell["Details item", "Item", "DetailsItem"],
            Cell["Details subitem", "Subitem", "DetailsSubitem"]
            }
          ],
    "Example"->
      Cell@
        CellGroupData[
          {
            Cell["Description", "Text"],
            Cell[BoxData@RowBox[{"FunctionName","[",RowBox[{"arg1",",", "arg2", ",", "..."}],"]"}], "Code"],
            Cell[BoxData[RowBox[{"result"}]], "Output", GeneratedCell->True]
            }
          ],
    "Related Functions"->
      Cell@
        CellGroupData[
          {
            Cell["See Also", "Subsection", "SeeAlso"],
            Cell[
              TextData@
                {
                  ButtonBox["Function1",
                    BaseStyle->{"Link", "Input"},ButtonData->"paclet:Pkg/ref/Function1"]," | ",
                  ButtonBox["Function2",
                    BaseStyle->{"Link", "Input"},ButtonData->"paclet:Pkg/ref/Function2"]
                  },
               "Text"
              ]
            }
          ],
    "Related Guides"->
      Cell@
        CellGroupData[
          {
            Cell["Related Guides", "Subsection", "Related"],
            Cell[
              TextData@ButtonBox["Guide 1",BaseStyle->"Link",ButtonData->"paclet:Pkg/guide/Guide1"],
              "Item"
              ],
            Cell[
              TextData@ButtonBox["Guide 2",BaseStyle->"Link",ButtonData->"paclet:Pkg/guide/Guide2"],
              "Item"
              ]
            }
          ],
    "Related Links"->
      Cell@
        CellGroupData[
          {
            Cell["Related Links", "Subsection", "RelatedLinks"],
            Cell[
              TextData@
                ButtonBox[
                  "Link 1",
                  BaseStyle->"Hyperlink",
                  ButtonData->{URL["https://google.com"],
                      None},
                  ButtonNote->"Link 1"
                  ],
              "Item"
              ],
            Cell[
              TextData@
                ButtonBox[
                  "Link 2",
                  BaseStyle->"Hyperlink",
                  ButtonData->{URL["https://paclets.github.io/PacletServer"],
                      None},
                  ButtonNote->"Link 2"
                  ],
              "Item"
              ]
            }
          ]
    |>;


(* ::Subsubsubsection::Closed:: *)
(*$sectionTemplates*)



$sectionTemplates=
  <|
    "Usage Section":>
      Cell@
        CellGroupData[
          {
            Cell["", "Subsection", "UsageSection"],
            $baseTemplates["Usage"],
            Cell["", "UsageSectionFooter"]
            }
          ],
    "Details Section":>
      Cell@
        CellGroupData[
          {
            Cell["Details", "Subsection", "DetailsSection"],
            $baseTemplates["Details"]
            },
          Closed
          ],
    "Examples Section":>
      Cell@
        CellGroupData[
          {
            Cell["Examples", "Subsection", "ExamplesSection"],
            Cell@
              CellGroupData[{
                  Cell["Basic Examples", "Subsubsection", "ExamplesSubsection"],
                  $baseTemplates["Example"]
                  }]
            }
          ],
    "Related Section":>
      Cell@
        CellGroupData[
          {
            $baseTemplates["Related Functions"],
            $baseTemplates["Related Guides"],
            $baseTemplates["Related Links"]
            }
          ],
    "Guide Section":>
      Cell@
        CellGroupData[
          {
            $miscTemplates["Divider"],
            Cell["Description", "Text"],
            $baseTemplates["Guide Line"],
            $baseTemplates["Guide Line"]
            }
          ]
    |>;


(* ::Subsubsubsection::Closed:: *)
(*$metaCell*)



$metaCell=
  Cell[
    BoxData[
      RowBox[{
          RowBox[{"(*"," ",
              RowBox[{"Markdown"," ","metadata"}]," ","*)"}],"\[IndentingNewLine]",
          RowBox[{"<|","\[IndentingNewLine]",
              RowBox[{
                  RowBox[{"\"Date\"","\[RuleDelayed]","Now"}],",","\[IndentingNewLine]",
                  RowBox[{"\"ExportOptions\"","\[Rule]",
                      RowBox[{"{","\[IndentingNewLine]",
                          RowBox[{"(*",
                              RowBox[{"\"UseImageInput\"","\[Rule]","True"}],"*)"}],"\[IndentingNewLine]","}"
                          }]
                      }]
                  }],"\[IndentingNewLine]",
              "|>"
              }]
          }]
      ],
    "Metadata"];


(* ::Subsubsubsection::Closed:: *)
(*$primaryTemplates*)



$primaryTemplates=
  <|
    "Symbol"->
      Cell@
        CellGroupData[
          {
            $metaCell,
            $miscTemplates["TitleBar"],
            Cell["FunctionName", "Section", "TitleSection"],
            $sectionTemplates["Usage Section"],
            $sectionTemplates["Details Section"],
            $sectionTemplates["Examples Section"],
            $sectionTemplates["Related Section"],
            $miscTemplates["Footer"]
            }
          ],
    "Guide"->
      Cell@
        CellGroupData[
          {
            $metaCell,
            $miscTemplates["TitleBar"],
            Cell["Guide Name", "Section", "TitleSection"],
            Cell["guide descriptions", "Text"],
            $sectionTemplates["Guide Section"],
            $miscTemplates["Divider"],
            $baseTemplates["Related Guides"],
            $baseTemplates["Related Links"],
            $miscTemplates["Footer"]
            }
          ],
    "Tutorial"->
      Cell@
        CellGroupData[
          {
            $metaCell,
            $miscTemplates["TitleBar"],
            Cell["Tutorial Name", "Section", "TitleSection"],
            $miscTemplates["Footer"]
            }
          ]
    |>;


(* ::Subsubsubsection::Closed:: *)
(*$NotebookTemplates*)



$NotebookTemplates=
  Join[
    $primaryTemplates,
    $sectionTemplates,
    $baseTemplates,
    $miscTemplates
    ]


(* ::Subsection:: *)
(*Notebook*)



(* ::Subsubsection::Closed:: *)
(*getNbData*)



getNbData[nb_, k_, default_]:=
  CurrentValue[nb, Flatten@{TaggingRules, k}, default];
getNbData[nb_, k_]:=
  CurrentValue[nb, Flatten@{TaggingRules, k}];


(* ::Subsubsection::Closed:: *)
(*setNbData*)



setNbData[nb_, k_, v_]:=
  CurrentValue[nb, Flatten@{TaggingRules, k}] =  v;


(* ::Subsubsection::Closed:: *)
(*taggingRules*)



$projNameTag=
  {"SimpleDocs", "Project", "Name"};
$projDirTag=
  {"SimpleDocs", "Project", "Directory"};
$projConfigTag=
  {"SimpleDocs", "Project", "Config"};


(* ::Subsubsection::Closed:: *)
(*getMeta*)



getMeta[nb_, k_]:=
  getNbData[nb, {"Metadata", ToLowerCase@k}];


(* ::Subsubsection::Closed:: *)
(*setMeta*)



getMeta[nb_, k_, v_]:=
  setNbData[nb, {"Metadata", ToLowerCase@k}, v];


(* ::Subsubsection::Closed:: *)
(*getProjectDialog*)



getProjectDialog[nb_:Automatic]:=
With[{baseStuff=getProjectLayout@nb},
  DialogInput[
    {
      projName=baseStuff[[1]],
      projDir=If[#===None, "", #]&@baseStuff[[2]],
      projConf=If[#===None, "", #]&@baseStuff[[3]]
      },
    Pane[
      Panel[
        Column[
          {
            EventHandler[
              InputField[Dynamic[projName],
                String,
                BoxID->"pname",
                FieldHint->"project name"
                ],
              "ReturnKeyDown":>DialogReturn@{projName, projDir, projConf}
              ],
            EventHandler[
              InputField[Dynamic[projDir],
                String,
                BoxID->"conf",
                FieldHint->"project directory (optional)"
                ],
              "ReturnKeyDown":>DialogReturn@{projName, projDir, projConf}
              ],
            EventHandler[
              InputField[Dynamic[projConf],
                String,
                BoxID->"conf",
                FieldHint->"config file/relative path (optional)"
                ],
              "ReturnKeyDown":>DialogReturn@{projName, projDir, projConf}
              ],
            DefaultButton[DialogReturn@{projName, projDir, projConf}]
            }
          ],
        "Specify project:",
        ImageSize->{Automatic, 150},
        Alignment->Center
        ],
      ImageSize->{265, 200},
      Alignment->Center
      ],
    NotebookDynamicExpression:>
      Refresh[
        FrontEndExecute@FrontEnd`MoveCursorToInputField[EvaluationNotebook[], "pname"], 
        None
        ],
CellInsertionPointCell->Automatic
    ]
  ];


(* ::Subsubsection::Closed:: *)
(*getPacletDialog*)



getPacletDialog[]:=
  DialogInput[
    {pacletName=""},
    Pane[
      Panel[
        Column[
          {
            EventHandler[
              InputField[Dynamic@pacletName,
                String,
                BoxID->"pname",
                FieldHint->"paclet name"
                ],
              "ReturnKeyDown":>DialogReturn@pacletName
              ],
            DefaultButton[DialogReturn@pacletName]
            }
          ],
        "Specify paclet:",
        ImageSize->{Automatic, 80},
        Alignment->Center
        ],
      ImageSize->{250, 100},
      Alignment->Center
      ],
    NotebookDynamicExpression:>
      Refresh[
        FrontEndExecute@FrontEnd`MoveCursorToInputField[EvaluationNotebook[], "pname"], 
        None
        ],
CellInsertionPointCell->Automatic
    ];


(* ::Subsubsection::Closed:: *)
(*getNBPaclet*)



getNBPaclet[nb_]:=
  getNbData[nb,
    {"SimpleDocs", "Paclet"},
    Replace[getNbData[nb, {"Paclet"}], Inherited->Automatic]
    ]


(* ::Subsubsection::Closed:: *)
(*getNBProject*)



getNBProject//Clear
getNBProject[nb_]:=
  getNbData[nb, $projNameTag];


(* ::Subsubsection::Closed:: *)
(*getNBProjectData*)



getNBProjectData[nb_]:=
  {
    getNBProject[nb],
    getNbData[nb, $projDirTag],
    getNbData[nb, $projConfigTag]
    };


(* ::Subsubsection::Closed:: *)
(*setNBProjectData*)



setNBProjectData[nb_, name_]:=
  If[projectQ[name],
    With[{dir=getProjectDir[name], conf=getProjectConfFile[name]},
      If[getNbData[nb, $projNameTag]=!=name,
        setNbData[nb, $projNameTag, name]
        ];
      If[getNbData[nb, $projDirTag]=!=dir,
        setNbData[nb, $projDirTag, dir]
        ];
      If[getNbData[nb, $projConfigTag]=!=conf,
        setNbData[nb, $projConfigTag, conf]
        ];
      ]
    ];


(* ::Subsubsection::Closed:: *)
(*getNBProjectName*)



(* ::Text:: *)
(*
	Might need a few updates... It\[CloseCurlyQuote]s a little bit cobbled together right now.
*)



getNBProjectName[nb_, proj_:None]:=
  Module[
    {
      projName=proj
      },
    If[!projectQ@projName, 
      projName=getNBProject[nb]
      ];
    EnsureLoadProject[nb];
    If[!projectQ[projName],
      projName=SetNotebookProject[nb, True];
      ];
    EnsureLoadProject[nb];
    setNBProjectData[nb, projName];
    projName
    ];


(* ::Subsubsection::Closed:: *)
(*SetNotebookProject*)



SetNotebookProject//Clear
SetNotebookProject[nb_, auto:True|False:False]:=
  Module[
    {
      projLoc=If[auto, Quiet@getFileProject[NotebookFileName[nb]]],
      projConf,
      projName,
      projData
      },
    If[StringQ@projLoc,
      EnsureLoadProject[projLoc]
      ];
    If[!projectQ@projLoc,
      projLoc=getProjectDialog[nb];
      If[projLoc=!=$Canceled,
        {projName, projLoc, projConf}=projLoc
        ],
      projName=getProjectName@projLoc;
      projLoc=.
      ];
    projData=
      If[StringQ@projLoc,
        EnsureLoadProject[projName, projLoc, projConf],
        EnsureLoadProject[projName]
        ];
    If[Length[projData]==3,
      {projName, projLoc, projConf}=projData
      ];
    If[StringQ@projName,
      setNbData[nb, $projNameTag, projName];
      setNbData[nb, $projDirTag, projLoc];
      setNbData[nb, $projConfigTag, projConf];
      projName,
      $Failed
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*prepNotebookForDocs*)



(* ::Text:: *)
(*
	For now we\[CloseCurlyQuote]re just going to assume we only go up one level before finding the docs notebook
*)



prepNotebookForDocs[nb_]:=
  Notebook[
    DeleteCases[
      #[[1]],
      Cell[_, "Metadata", ___],
      \[Infinity],
      1
      ],
    Flatten@{
      FilterRules[
        Flatten[List@@#[[2;;]]], 
        Except[ScreenStyleEnvironment|StyleDefinitions|Visible]
        ],
      Visible->True,
      ScreenStyleEnvironment->"Working",
      StyleDefinitions->
        Notebook[
          {
            (*Cell[
							StyleData[
								StyleDefinitions\[Rule]
									FrontEnd`FileName[{"SimpleDocs"}, "SimpleDocs.nb"]
								]
							],*)
            Cell[
              StyleData[
                StyleDefinitions->
                  FrontEnd`FileName[{ParentDirectory[]}, "SimpleDocsStyles.nb"]
                ]
              ],
            Cell[
              StyleData[
                StyleDefinitions->
                  FrontEnd`FileName[{ParentDirectory[], ParentDirectory[]}, "SimpleDocsStyles.nb"]
                ]
              ],
            Cell[StyleData[StyleDefinitions->"Default.nb"]],
            Cell[StyleData[All, "Editing"], MenuSortingValue->None]
            },
          StyleDefinitions->"PrivateStylesheetFormatting.nb"
          ]
      }
    ]&@NotebookGet[nb]


(* ::Subsubsection::Closed:: *)
(*SaveNotebookToDocumentation*)



(* ::Text:: *)
(*
	New version of SaveNotebookToPaclet that makes use of the more flexible project structure
*)



SaveNotebookToDocumentation//Clear;
SaveNotebookToDocumentation[nb_, proj_:Automatic]:=
  Module[
    {
      projName=proj,
      projDir,
      projConf,
      fname
      },
    projName=getNBProjectName[nb, projName];
    fname=getPacletSaveFileName[projName, nb];
    If[StringQ@fname&&DirectoryQ@DirectoryName@fname,
      CopyFile[
        PackageFilePath["FrontEnd", "StyleSheets", "SimpleDocs", "SimpleDocs.nb"],
        FileNameJoin@{
          Nest[DirectoryName, fname, 2],
          "SimpleDocsStyles.nb"
          },
        OverwriteTarget->True
        ];
      CopyFile[
        PackageFilePath["FrontEnd", "StyleSheets", "SimpleDocs", "SimpleDocs.nb"],
        FileNameJoin@{
          Nest[DirectoryName, fname, 3],
          "SimpleDocsStyles.nb"
          },
        OverwriteTarget->True
        ];
      (*Quiet@*)Export[fname, prepNotebookForDocs[nb]]
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*SaveNotebookToProject*)



(* ::Text:: *)
(*
	New version of SaveNotebookToPacletProject that makes use of the more flexible project structure
*)



SaveNotebookToProject//Clear
SaveNotebookToProject[nb_, proj_:Automatic]:=
  Module[
    {
      projName=proj,
      pac,
      fname
      },
    projName=getNBProjectName[nb, projName];
    fname=getProjectSaveFileName[projName, nb];
    If[StringQ@fname,
      If[!DirectoryQ@DirectoryName@fname,
        (* should I need to do this...? *)
        CreateDirectory[DirectoryName@fname, CreateIntermediateDirectories->True]
        ];
      NotebookSave[nb, fname],
      PackageRaiseException[
        Automatic,
        "Save location `` is invalid",
        fname
        ]
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*SetNotebookPaclet*)



SetNotebookPaclet[nb_]:=
  Module[
    {pacletLoc=getPacletDialog[]},
    If[StringLength@pacletLoc>0,
      setNbData[nb, {"SimpleDocs", "Paclet"}, pacletLoc],
      pacletLoc=None
      ];
    pacletLoc
    ]


(* ::Subsubsection::Closed:: *)
(*getNotebookPaclet*)



getNotebookPaclet[nb_, ploc_:Automatic]:=
  Module[
    {
      pacletLoc=ploc,
      pac
      },
    If[!StringQ@pacletLoc, 
      pacletLoc=getNBPaclet[nb]
      ];
    If[!StringQ[pacletLoc], 
      pacletLoc=SetNotebookPaclet[nb];
      ];
    If[StringQ@pacletLoc,
      pac=PacletManager`PacletFind[pacletLoc];
      If[Length@pac>0, pac=First@pac, pac=None],
      pac=None
      ];
    pac
    ]


(* ::Subsubsection::Closed:: *)
(*SaveNotebookToPaclet*)



SaveNotebookToPaclet//Clear;
SaveNotebookToPaclet[nb_, ploc_:Automatic]:=
  Module[
    {
      pacletLoc=ploc,
      pac,
      fname
      },
    If[!StringQ@pacletLoc, 
      pacletLoc=getNBPaclet[nb]
      ];
    If[!StringQ[pacletLoc], 
      pacletLoc=SetNotebookPaclet[nb];
      ];
    If[StringQ@pacletLoc,
      pac=PacletManager`PacletFind[pacletLoc];
      If[Length@pac>0, pac=First@pac, pac=None];
      If[pac=!=None,
        fname=getPacletSaveFileName[pac, nb];
        Export[
          fname,
          Notebook[#[[1]],
            FilterRules[
              Flatten@{List@@#[[2;;]], ScreenStyleEnvironment->"Working"},
               Except[ScreenStyleEnvironment]
              ]
            ]&@NotebookGet[nb] 
          ]
        ]
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*SaveNotebookToPacletProject*)



SaveNotebookToPacletProject//Clear
SaveNotebookToPacletProject[nb_, ploc_:Automatic]:=
  Module[
    {
      pacletLoc=ploc,
      pac,
      fname
      },
    If[!StringQ@pacletLoc, 
      pacletLoc=getNBPaclet[nb]
      ];
    If[!StringQ[pacletLoc], 
      pacletLoc=SetNotebookPaclet[nb];
      ];
    If[StringQ@pacletLoc,
      pac=PacletManager`PacletFind[pacletLoc];
      If[Length@pac>0, pac=First@pac, pac=None];
      If[pac=!=None,
        fname=getSiteSaveFileName[pac, nb];
        NotebookSave[nb, fname]
        ]
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*SaveNotebookMarkdown*)



(* ::Subsubsubsection::Closed:: *)
(*customMDExporter*)



customMDExporter//Clear
customMDExporter[pi_, c:Cell[_, "Text", "Footer", ___]]:=
  {
    Cell["", "PageBreak"],
    c
    };
customMDExporter[pi_, e_]:=e


(* ::Subsubsubsection::Closed:: *)
(*mergeCellStyles*)



mergeCellStyles[md_]:=
  Module[
    {
      sub=
        Lookup[Select[Lookup[md, "ExportOptions", {}], OptionQ], "CellStyles", {}],
      autof
      },
    autof=Lookup[sub, Automatic, None];
    {ParentList, 
      "Input", 
      Automatic->
        If[autof===None, 
          customMDExporter,
          customMDExporter[#, autof[##]]&
          ]
      }
    ]


(* ::Subsubsubsection::Closed:: *)
(*SaveNotebookMarkdown*)



SaveNotebookMarkdown[nb_]:=
  Module[
    {
      md=MarkdownNotebookMetadata@nb,
      projName=getNBProjectName[nb, None],
      sname
      },
    md=
      Merge[
        {
          Replace[md,
            ("CellStyles"->_)->Nothing,
            4
            ],
          "ExportOptions"->
            {
              "PacletLinkResolutionFunction"->
                Function[l, 
                  "../"<>
                  URLBuild[
                    Join@@
                      SplitBy[
                        URLParse[l, "Path"],
                        #=="ref"||#=="guide"||#=="tutorial"&
                        ][[-2;;]]
                    ]<>".html"
                  ],
              "CellStyles"->mergeCellStyles[md],
              "ContentPathExtension"->".."
              },
          "Title"->getMeta[nb, "title"],
          "Date"->
            Replace[getMeta[nb, "built"], 
              {
                s_String:>DateObject@ToExpression[s],
                l_List:>DateObject[l]
                }
              ],
          getProjectProp[projName, "MarkdownOptions", {}],
          Flatten@{
              Replace[
                getNbData[nb, {"Metadata"}],
                Except[_?OptionQ]:>{}
                ]
              }
          },
        Which[
          AllTrue[#, OptionQ], 
            Normal@Merge[#, First],
          AllTrue[#, ListQ],
            Join@@#,
          Length@#==1,
            First@#,
          ListQ@#[[2]],
            Prepend[#[[2]], #[[1]]],
          True,
            First@#
          ]&
        ];
  sname=getSiteSaveFileName[projName, nb];
  If[StringQ@sname,
    NotebookMarkdownSave[nb, 
      DirectoryName@sname,
      Sequence@@Normal@md
      ],
    NotebookMarkdownSave[nb, Sequence@@Normal@md]
    ]
  ]


(* ::Subsubsection::Closed:: *)
(*PrepareNotebookMetadata*)



PrepareNotebookMetadata[nb_]:=
  Module[
    {
      projName,
      baseData
      },
    projName=getNBProjectName[nb];
    baseData=
      getProjectProp[projName, "Metadata", <||>];
    Normal@
      Merge[
        {
          DocMetadata[nb],
          baseData
          },
        Last
        ]
    ]


(* ::Subsubsection::Closed:: *)
(*PopulateNotebookMetadata*)



capitalize=ToUpperCase[StringTake[#, {1}]]<>StringDrop[#, 1]&


PopulateNotebookMetadata[nb_]:=
  Module[{md=PrepareNotebookMetadata[nb]},
    setNbData[nb, {"Metadata"}, md];
    setNbData[nb, {"ColorType"}, 
      capitalize[Lookup[md, "type", "message"]]<>"Color"];
    ]


(* ::Subsubsection::Closed:: *)
(*populateNotebookMetadataDynamic*)



populateNotebookMetadataDynamic[ev_]:=
  MessageDialog[
    DynamicModule[
      {},
      ":)",
      Initialization:>{
        PopulateNotebookMetadata[ev],
        NotebookClose[EvaluationNotebook[]]
        },
      SynchronousInitialization->True
      ],
    Visible->False
    ]


(* ::Subsubsection::Closed:: *)
(*ClearNotebookMetadata*)



ClearNotebookMetadata[nb_]:=
  setNbData[nb, {"Metadata"},
      Thread[Map[ToLowerCase, Flatten@Values@$MetadataMap]->Automatic]
      ];


(* ::Subsubsection::Closed:: *)
(*CheckSaveNotebook*)



CheckSaveNotebook[nb_]:=
  Module[
    {
      saveMD,
      saveDoc
      },
    saveMD=
      getNbData[nb, {"SimpleDocs", "MarkdownAutosave"}, False];
    saveDoc=
      getNbData[nb, {"SimpleDocs", "DocumentationAutosave"}, False];
    If[TrueQ@saveDoc,
      SaveNotebookToDocumentation[nb]
      ];
    If[TrueQ@saveMD,
      SaveNotebookMarkdown[nb]
      ];
    ]


(* ::Subsection:: *)
(*Templates*)



(* ::Subsubsection::Closed:: *)
(*CreateTemplateNotebook*)



$ctnMap=
  <|
    "Symbol"->SymbolNotebookTemplate,
    "Guide"->GuideNotebookTemplate,
    "Tutorial"->TutorialNotebookTemplate,
    "TableOfContents" -> TableOfContentsNotebook
    |>;


CreateTemplateNotebook//ClearAll
CreateTemplateNotebook[
  type:(Alternatives@@Keys[$ctnMap]), 
  thing_, ops:OptionsPattern[]
  ]:=
  CreateDocument[
    Lookup[$ctnMap, type][thing, ops]
    ];
CreateTemplateNotebook[thing_Symbol]:=
  CreateTemplateNotebook["Symbol", thing];
CreateTemplateNotebook[thing_String]:=
  If[NameQ[thing],
    ToExpression[thing, StandardForm,
      Function[Null, CreateTemplateNotebook["Symbol", #], HoldAllComplete]
      ],
    CreateTemplateNotebook["Guide", thing]
    ];
CreateTemplateNotebook[e_, r___]:=
  CreateTemplateNotebook[Evaluate@e, r]/;
    MatchQ[e, _String|_Symbol];
CreateTemplateNotebook[type_, thing_]:=
  CreateTemplateNotebook[Evaluate@type, thing]/;
    KeyExistsQ[$ctnMap, type];
CreateTemplateNotebook~SetAttributes~HoldAll;


PackageAddAutocompletions[
  CreateTemplateNotebook,
  {Keys@$ctnMap}
  ]


(* ::Subsubsection::Closed:: *)
(*SymbolNotebookTemplate*)



(* ::Subsubsubsection::Closed:: *)
(*formatUsageSection*)



formatUsageSection[u_]:=
  Cell@
    CellGroupData[Flatten@{
      Cell["", "UsageSection"],
      Replace[u,
        {a_, b_}:>
          {
            Cell[
              BoxData@FrontEndExecute@FrontEnd`ReparseBoxStructurePacket[a], 
              "Code", 
              "UsageInput"
              ],
            Cell[
              b, 
              "Text", 
              "UsageText"
              ]
              },
        1
        ],
      Cell["", "UsageSectionFooter"]
      }]


(* ::Subsubsubsection::Closed:: *)
(*formatDetailsSection*)



formatDetailsSection[deets_]:=
  Cell@
    CellGroupData[
      Prepend[Cell["Details", "Subsection", "DetailsSection"]]@
        Replace[
          deets,
          {
            grid:{__List}:>
              Sequence@@Replace[grid,
                {
                  {a_}:>Cell[a, "Subitem", "DetailsItem"],
                  {a_, b_}:>
                    Sequence@@{
                      Cell[a, "Subitem", "DetailsItem"],
                      Cell[b, "Subsubitem", "DetailsItem"]
                      }
                  },
                1
                ],
            line_:>Cell[StringRiffle[line], "Item", "DetailsItem"]
            },
          1
          ],
      Closed
      ]


(* ::Subsubsubsection::Closed:: *)
(*formatExamplesSection*)



formatExamplesSection[ex_, d_:0]:=
  Module[{dooooop=True},
    If[d==0,
      Cell@
        CellGroupData[
          Prepend[Cell["Examples", "Subsection", "ExamplesSection"]]@
          #
          ]&,
      Identity
      ]@Replace[
          ex,
          {
            (a_->b_List):>
              Cell@
                CellGroupData[
                  Prepend[
                    Cell[a, "S"<>StringRepeat["ubs", d+2]<>"ection", "ExamplesSection"]
                    ]@formatExamplesSection[b, d+1],
                  If[dooooop, dooooop=False;Open, Closed]
                  ],
            (a_->b_):>
              Cell@
                CellGroupData[{
                  Cell[a, "Text", "ExamplesText"],
                  Cell[
                    BoxData@FrontEndExecute@
                      FrontEnd`ReparseBoxStructurePacket@b, "Code", "ExamplesInput"]
                  }]
            },
          1
          ]
    ]


(* ::Subsubsubsection::Closed:: *)
(*formatRelatedSection*)



formatRelatedSection[names_]:=
  Cell@CellGroupData[
    {
      Cell@
        CellGroupData[
          {
            Cell["See Also", "Subsection", "SeeAlso"],
            Cell[
              TextData@
                Riffle[
                  ButtonBox[#,
                    BaseStyle->{"Link", "Input"},ButtonData->"paclet:ref/"<>#
                    ]&/@names,
                  " | "
                  ],
               "Text"
              ]
            }
          ],
      $baseTemplates["Related Guides"],
      $baseTemplates["Related Links"]
      }
    ]


(* ::Subsubsubsection::Closed:: *)
(*splitUsageCalls*)



splitUsageCalls[sname_, use_]:=
  StringSplit[use, 
    {
      k:Shortest[
        ((StartOfLine|StartOfString)~~a:Except["["]..~~"["~~b___~~"]")/;
          (
            StringContainsQ[a, sname]&&
              StringCount[b, "["]==StringCount[b, "]"]
            )
        ]:>
        k,
      ((StartOfLine|StartOfString)~~sname~~" "):>
       StringTrim[sname]
     }
    ]


(* ::Subsubsubsection::Closed:: *)
(*getUsageMessages*)



getUsageMessages[s_]:=
  Module[
    {
      ubase,
      usplits
      },
    ubase=s::usage;
    If[!StringQ@ubase,
      usplits=None,
      usplits=StringTrim@splitUsageCalls[SymbolName[Unevaluated@s], ubase];
      If[Length@usplits>1,
        usplits=
          Replace[
            Partition[usplits, UpTo[2]],
            {a_}:>{a, ""},
            1
            ],
        usplits=ubase
        ]
      ];
    usplits
    ];
getUsageMessages~SetAttributes~HoldFirst;


(* ::Subsubsubsection::Closed:: *)
(*SymbolNotebookTemplate*)



SymbolNotebookTemplate//Clear
Options[SymbolNotebookTemplate]=
  Options[Notebook];
SymbolNotebookTemplate[
  s_Symbol, 
  parent:Except[_?OptionQ]:None, 
  ops:OptionsPattern[]
  ]:=
  Module[
    {
      bits,
      use1,
      use,
      deets,
      exams,
      similar,
      keys,
      meta,
      nb
      },
    use1=getUsageMessages[s];
    keys={"Details", "Examples", "RelatedFunctions"};
    If[Length[use1]===0,
      PrependTo[keys, "UsageMessages"]
      ];
    bits=GenerateFunctionInfo[s, "Keys"->keys];
    {use, deets, exams, similar}=
      If[Length@use1>0, Prepend[use1], Identity]@Lookup[bits, keys];
    If[Length@use1===0,
      use=splitUsageCalls[SymbolName[Unevaluated[s]], use];
      If[StringQ@use1&&Length[use]===0,
        use = {{SymbolName[Unevaluated[s]], use1}}
        ]
      ];
    meta=AssociationThread[ToLowerCase@Flatten@Values@$MetadataMap, Automatic];
    meta["label"]=SymbolName[Unevaluated@s];
    meta["context"]=Context[s];
    meta["type"]="Symbol";
    nb=
      Notebook[
        {
          $metaCell,
          $miscTemplates["TitleBar"]/.
            "<Context>"->StringDelete[meta["context"], "`"]<>" Symbol",
          Cell[meta["label"], "Section", "SymbolName"],
          formatUsageSection[use],
          formatDetailsSection[deets],
          formatExamplesSection[exams],
          formatRelatedSection[similar],
          $NotebookTemplates["Footer"]
          },
        Flatten@{
          StyleDefinitions->FrontEnd`FileName[{"SimpleDocs"}, "SimpleDocs.nb"],
          TaggingRules->Flatten@{
            "Metadata"->DocMetadata@Normal@meta,
            If[MatchQ[parent, _NotebookObject],
              "SimpleDocs"->
                getNbData[parent, {"SimpleDocs"}],
              Nothing
              ],
            "ColorType"->"SymbolColor",
            Replace[OptionValue[TaggingRules], Except[_?OptionQ]:>{}]
            },
          ScreenStyleEnvironment->"Editing",
          FilterRules[
            {ops},
            Except[StyleDefinitions|TaggingRules|ScreenStyleEnvironment]
            ]
          }
        ]
    ];
SymbolNotebookTemplate~SetAttributes~HoldFirst


(* ::Subsubsection::Closed:: *)
(*GuideNotebookTemplate*)



GuideNotebookTemplate//Clear
Options[GuideNotebookTemplate]=
  Options[Notebook];
GuideNotebookTemplate[name_String, 
  parent:Except[_?OptionQ]:None, ops:OptionsPattern[]
  ]:=
  Module[
    {
      cleanName,
      meta,
      nb
      },
    meta=AssociationThread[ToLowerCase@Flatten@Values@$MetadataMap, Automatic];
    cleanName=StringDelete[name, Except[WordCharacter]|"$"];
    meta["label"]=cleanName;
    meta["type"]="Guide";
    nb=
      Notebook[
        {
          $metaCell,
          $miscTemplates["TitleBar"]/.
            "<Context>"->"Guide",
          Cell[name, "Section", "GuideName"],
          Cell["guide descriptions", "Text"],
          $sectionTemplates["Guide Section"],
          $miscTemplates["Divider"],
          $NotebookTemplates["Related Guides"],
          $NotebookTemplates["Related Links"],
          $NotebookTemplates["Footer"]
          },
        {
          StyleDefinitions->FrontEnd`FileName[{"SimpleDocs"}, "SimpleDocs.nb"],
          TaggingRules->Flatten@{
            "Metadata"->DocMetadata@Normal@meta,
            If[MatchQ[parent, _NotebookObject],
              "SimpleDocs"->getNbData[parent, {"SimpleDocs"}],
              Nothing
              ],
            "ColorType"->"GuideColor",
            Replace[OptionValue[TaggingRules], Except[_?OptionQ]:>{}]
            },
          ScreenStyleEnvironment->"Editing",
          FilterRules[
            {ops},
            Except[StyleDefinitions|TaggingRules|ScreenStyleEnvironment]
            ]
          }
        ]
    ]


(* ::Subsubsection::Closed:: *)
(*TutorialNotebookTemplate*)



TutorialNotebookTemplate//Clear
Options[TutorialNotebookTemplate]=
  Options[Notebook];
TutorialNotebookTemplate[name_String, 
  parent:Except[_?OptionQ]:None, ops:OptionsPattern[]
  ]:=
  Module[
    {
      cleanName,
      meta,
      nb
      },
    meta=AssociationThread[ToLowerCase@Flatten@Values@$MetadataMap, Automatic];
    cleanName=StringDelete[name, Except[WordCharacter]|"$"];
    meta["label"]=cleanName;
    meta["type"]="Tutorial";
    nb=
      Notebook[
        {
          $metaCell,
          $miscTemplates["TitleBar"]/.
            "<Context>"->"Tutorial",
          Cell[name, "Section", "TutorialName"],
          Cell["Tutorial text...", "Text"],
          $miscTemplates["Divider"],
          $NotebookTemplates["Related Guides"],
          $NotebookTemplates["Related Links"],
          $NotebookTemplates["Footer"]
          },
        Flatten@{
          StyleDefinitions->FrontEnd`FileName[{"SimpleDocs"}, "SimpleDocs.nb"],
          TaggingRules->Flatten@{
            "Metadata"->DocMetadata@Normal@meta,
            If[MatchQ[parent, _NotebookObject],
              "SimpleDocs"->getNbData[parent, {"SimpleDocs"}],
              Nothing
              ],
            "ColorType"->"TutorialColor",
            Replace[OptionValue[TaggingRules], Except[_?OptionQ]:>{}]
            },
          ScreenStyleEnvironment->"Editing",
          FilterRules[
            {ops},
            Except[StyleDefinitions|TaggingRules|ScreenStyleEnvironment]
            ]
          }
        ]
    ]


(* ::Subsubsection::Closed:: *)
(*SampleTemplateNotebook*)



(* ::Subsubsubsection::Closed:: *)
(*Symbol*)



SampleTemplateNotebook["Symbol", ops:OptionsPattern[]]:=
  Block[{SamplePaclet`Sym, SamplePaclet`Sym1, SamplePaclet`Sym2},
    SamplePaclet`Sym::usage="sample function";
    SamplePaclet`Sym::msg="sample message";
    SamplePaclet`Sym[arg_]:=Null;
    SamplePaclet`Sym~SetAttributes~Temporary;
    SamplePaclet`Sym1=1;
    SamplePaclet`Sym2=2;
    CreateTemplateNotebook["Symbol", SamplePaclet`Sym, ops]
    ]


(* ::Subsubsubsection::Closed:: *)
(*Guide*)



SampleTemplateNotebook["Guide", ops:OptionsPattern[]]:=
  CreateTemplateNotebook["Guide", "Sample Guide", ops];


(* ::Subsubsubsection::Closed:: *)
(*Tutorial*)



SampleTemplateNotebook["Tutorial", ops:OptionsPattern[]]:=
  CreateTemplateNotebook["Tutorial", "Sample Tutorial", ops];


(* ::Subsubsection::Closed:: *)
(*TableOfContentsNotebook*)



(* ::Subsubsubsection::Closed:: *)
(*makeSymCell*)



makeSymCell[sym_, usage_]:=
  Module[
    {
      sn=SymbolName[sym],
      baseName=StringSplit[Context@sym, "`"][[1]],
      u=sym::usage
      },
    Cell[
      TextData[{
       ButtonBox[sn,
        BaseStyle->"Link",
        ButtonData->"paclet:"<>baseName<>"/ref/Function1"
        ],
       " - ",
       usage
      }], 
      "Text"
      ]
    ]


(* ::Subsubsubsection::Closed:: *)
(*TableOfContentsNotebook*)



TableOfContentsNotebook//Clear
TableOfContentsNotebook[name_->symbols_, parent_:None]:=
    Module[
      {
        cells,
        usages=
          StringSplit[
            Replace[
              Replace[
                Thread@Hold[symbols], 
                Hold[s_]:>
                  Replace[s::usage, Except[_String]->""],
                1
                ],
              ""->"No usage",
              1
              ],
            "\n"
            ][[All, 1]],
        symGroups,
        meta,
        cleanName
        },
      Block[symbols,
        meta=AssociationThread[ToLowerCase@Flatten@Values@$MetadataMap, Automatic];
        cleanName=StringDelete[name, Except[WordCharacter]|"$"];
        meta["label"]=cleanName;
        meta["type"]="Guide";
        symGroups=
          KeyMap[StringReplace["`"->" "]]@
            GroupBy[
              Thread[{symbols, usages}], Context[Evaluate@#[[1]]]&];
        Notebook[
          Flatten@{
            $metaCell,
            $miscTemplates["TitleBar"]/.
              "<Context>"->"Guide",
            Cell[name, "Section", "GuideName"],
            KeyValueMap[
              Cell[
                CellGroupData[
                  Flatten@{
                    Cell["", "PageBreak",                        
                     PageBreakAbove->False,
                     PageBreakBelow->False
                     ],
                    Cell[#, "Subsection"],
                    makeSymCell@@@#2
                    }
                  ]
                ]&,
              symGroups
              ],
            $miscTemplates["Divider"],
            $NotebookTemplates["Related Guides"],
            $NotebookTemplates["Related Links"],
            $NotebookTemplates["Footer"]
            },
          {
            StyleDefinitions->FrontEnd`FileName[{"SimpleDocs"}, "SimpleDocs.nb"],
            TaggingRules->{
              "Metadata"->DocMetadata@Normal@meta,
              If[MatchQ[parent, _NotebookObject],
                "SimpleDocs"->getNbData[parent, {"SimpleDocs"}],
                Nothing
                ],
              "ColorType"->"GuideColor"
              },
            ScreenStyleEnvironment->"Editing"
            }
          ]
      ]
    ];
TableOfContentsNotebook~SetAttributes~HoldRest;


(* ::Subsection:: *)
(*GUI*)



(* ::Subsubsection::Closed:: *)
(*$MetadataEditor*)



(* ::Subsubsubsection::Closed:: *)
(*boxGrid*)



boxGrid=
Column[
KeyValueMap[
OpenerView[
{#, 
Grid[
Map[
{#,
With[{tag=ToLowerCase@StringDelete[#, " "]},
InputField[
Dynamic@
                    CurrentValue[EvaluationNotebook[], 
                      {TaggingRules,"Metadata", tag}, Automatic]
]
]
}&,
#2
],
Alignment->Left
]
}
]&,
$MetadataMap
]
];


(* ::Subsubsubsection::Closed:: *)
(*showButton*)



hideButton[Hold[var_]]:=
  Button["",
    var=False, 
    ImageSize->{7, 7},
    FrameMargins->0,
    ImageMargins->0,
    Appearance->
      {
        "Default"->
          Image[ToExpression[FrontEndResource["FEBitmaps", "SquareMinusIconSmall"]]]
        }
    ]


showButton[Hold[var_]]:=
  Button["",
    var=True, 
    ImageSize->{7, 7},
    FrameMargins->0,
    ImageMargins->0,
    Appearance->
      {
        "Default"->
          Image[ToExpression[FrontEndResource["FEBitmaps", "SquarePlusIconSmall"]]]
        }
    ]


(* ::Subsubsubsection::Closed:: *)
(*$MetadataEditor*)



$MetadataEditor=
  DynamicModule[{show},
    With[
      {
        bg=boxGrid, 
        hb=hideButton[Hold@show], sb=showButton[Hold@show]
        },
      Dynamic@
        Grid[
          {
            {
              If[TrueQ@show, hb, sb], 
              Item["Metadata", ItemSize->Scaled[.15]],
              Item[
                ButtonBar[
                  {
                    "Populate":>
                      (
                        Needs["SimpleDocs`"];
                        populateNotebookMetadataDynamic[EvaluationNotebook[]]
                        ),
                    "Clear":>
                      (
                        Needs["SimpleDocs`"];
                        ClearNotebookMetadata[EvaluationNotebook[]]
                        )
                    },
                  ImageSize->{100, Automatic}
                  ],
                Alignment->Right,
                ItemSize->Scaled[.8]
                ]
              },
            {Null, If[TrueQ@show, bg], SpanFromLeft}
            },
          Alignment->Left
          ]
      ]
    ];


(* ::Subsubsection::Closed:: *)
(*$InsertionMenu*)



(* ::Subsubsubsection::Closed:: *)
(*$insertTemplate*)



$insertionMenuTemplates=
  Join@@
    Replace[
      Riffle[
        KeyValueMap[
          #:>NotebookWrite[InputNotebook[], #2]&,
          #
          ]&/@{
          $primaryTemplates,
          $sectionTemplates,
          $baseTemplates,
          $miscTemplates
          },
        Delimiter
        ],
      Delimiter->{Delimiter},
      1
      ]


(* ::Subsubsubsection::Closed:: *)
(*$InsertionMenu*)



$thumb1=
  RawBoxes@
    DynamicBox[
      FEPrivate`ImportImage[
        FrontEnd`FileName[
          {"Misc"},
          "CellInsertionPointBitmap.png"
          ]
        ]
      ];


$thumb2=
  Pane[
    Framed[
      Style["+", Large, Gray], 
      Background->GrayLevel[.95], 
      FrameStyle->Gray, 
      RoundingRadius->5,
      ImageSize->{80, 40},
      FrameMargins->{{25, 25}, {5, 5}},
      Alignment->Center
      ],
    {80, 26},
    Alignment->{Left, Top},
    BaselinePosition->Bottom,
    ImageSizeAction->"Clip",
    ScrollPosition->{150, 50},
    Scrollbars->False
    ];


$InsertionMenu=
  ActionMenu[
    $thumb2,
    $insertionMenuTemplates,
    Appearance->None
    ]


(* ::Subsubsection::Closed:: *)
(*$HamburgerMenu*)



$HamburgerMenu=
  ActionMenu[
    Button["\[Congruent]",None,Appearance->None, ImageSize->{50, 35}],
    {
      "Save Documentation":>
        (
          Needs["SimpleDocs`"];
          NotebookOpen@SaveNotebookToDocumentation[EvaluationNotebook[]]
          ),
      "Save To Project":>
        (
          Needs["SimpleDocs`"];
          SaveNotebookToProject[EvaluationNotebook[]]
          ),
      "Save Markdown":>
        (
          Needs["SimpleDocs`"];
          NotebookOpen@SaveNotebookMarkdown[EvaluationNotebook[]]
          ),
      Delimiter,
      "Set Project":>
        (
          Needs["SimpleDocs`"];
          SetNotebookProject[EvaluationNotebook[]]
          ),
      "Update PacletInfo":>
        (
          Needs["SimpleDocs`"];
          Replace[SetPacletInfo[EvaluationNotebook[]],
            s_String:>NotebookOpen@s
            ]
          ),
      "Bundle Paclet":>
        (
          Needs["SimpleDocs`"];
          Replace[BundlePaclet[EvaluationNotebook[]],
            s_String:>SystemOpen@DirectoryName@s
            ]
          ),
      Delimiter,
      "New Symbol":>
        (
          Needs["SimpleDocs`"];
          SampleTemplateNotebook["Symbol"]
          ),
      "New Guide":>
        (
          Needs["SimpleDocs`"];
          SampleTemplateNotebook["Guide"]
          ),
      "New Tutorial":>
        (
          Needs["SimpleDocs`"];
          SampleTemplateNotebook["Tutorial"]
          ),
      Delimiter,
      "Open SiteConfig":>
        (
          Needs["SimpleDocs`"];
          OpenDocsSiteConfig[EvaluationNotebook[]]
          ),
      "Build Site":>
        (
          Needs["SimpleDocs`"];
          BuildNotebookDocsSite[EvaluationNotebook[]]
          )
      },
    Appearance->None,
    Method->"Queued"
    ];


(* ::Subsubsection::Closed:: *)
(*$AutosaveButtons*)



$AutosaveButtons=
  Style[#, PageWidth->Infinity]&@
  Grid[
    {
      {Item["Save", Alignment->Left], SpanFromLeft},
      {Null,
        Item[
          Grid[
          {
            {
              ".md:",
              Checkbox[
                Dynamic@
                  CurrentValue[
                    EvaluationNotebook[], 
                    {TaggingRules, "SimpleDocs", "MarkdownAutosave"},
                    False
                    ]
                ]
              },
            {
              ".nb:",
              Checkbox[
                Dynamic@
                  CurrentValue[
                    EvaluationNotebook[], 
                    {TaggingRules, "SimpleDocs", "DocumentationAutosave"},
                    False
                    ]
                ]
              }
            },
          Spacings->{0, -.1}
          ],
        Alignment->Right
        ]
        }
      }
    ]


(* ::Subsubsection::Closed:: *)
(*$DockedCell*)



$dockedCell=
  Grid[
    {
      {
        Item[
          Framed[
            $MetadataEditor, 
            ImageSize->{Scaled[1], {55, 1000}},
            Background->White,
            RoundingRadius->5,
            BaseStyle->"Panel",
            FrameStyle->GrayLevel[.8]
            ], 
          ItemSize->{Scaled[.7], Automatic}
          ], 
        Item["", ItemSize->Scaled[.15]],
        Item[
          Pane[$AutosaveButtons,
            {Scaled[1], 50},
            Alignment->{Right, Top},
            ImageSizeAction->"ShrinkToFit"
            ],
          ItemSize->{Scaled[.1], All},
          Alignment->{Right, Top}
          ],
        Item[$HamburgerMenu(*ItemSize\[Rule]Scaled[.03]*),Alignment->Right]
        }
      }, 
    Alignment->{Left, Top}, 
    BaseStyle->{FontFamily->"Helvetica", FontSize->14}
    ];


$DockedCell=
  {
    Cell[
      BoxData[ToBoxes@$dockedCell],
      "Output",
      Background->GrayLevel[.95],
      CellFrameColor->Gray,
      CellFrame->{{0, 0}, {1, 0}}
      ],
    Cell[
      BoxData@ToBoxes@$InsertionMenu,
      "Output",
      Background->None,
      TextAlignment->Center,
      CellFrame->None,
      CellMargins->
        {
          {
            FEPrivate`Part[
              FrontEnd`AbsoluteCurrentValue[WindowSize],
              1
              ]-120, 
            35
            }, 
          {0, -2}
          }
      ]
    }


(* ::Subsection:: *)
(*Paclets*)



(* ::Subsubsection::Closed:: *)
(*SetPacletInfo*)



(* ::Text:: *)
(*
	Not sure how best to fit this into the whole new \[OpenCurlyDoubleQuote]project\[CloseCurlyDoubleQuote] structure. There might not always be a paclet to anchor to?
*)



SetPacletInfo//Clear
SetPacletInfo[pac:_PacletManager`Paclet]:=
  Module[{pi=PacletManager`PacletInformation@pac},
    PacletExecute["GeneratePacletInfo",
      Lookup[pi, "Location"],
      "Version"->Lookup[pi, "Version"]
      ]
    ];
SetPacletInfo[projName_]:=
  Module[
    {
      buildDir
      },
    buildDir=getProjectBuildDir[projName];
    If[TrueQ@PacletExecute["ValidDirectoryQ", buildDir],
      SetPacletInfo[PacletExecute["Paclet", buildDir]],
      If[DirectoryQ[buildDir],
        PacletExecute["GeneratePacletInfo",
          buildDir,
          "Version"->"0.0.0"
          ]
        ]
      ]
    ];
SetPacletInfo[nb_NotebookObject, ploc_:Automatic]:=
  Module[
    {
      proj=getNBProjectName[nb, ploc]
      },
    SetPacletInfo[proj]
    ]


(* ::Subsubsection::Closed:: *)
(*BundlePaclet*)



BundlePaclet//Clear
BundlePaclet[pac:_PacletManager`Paclet]:=
  Module[{pi=PacletManager`PacletInformation@pac},
    PacletExecute["Bundle", Lookup[pi, "Location"],
      "RemovePatterns"->{"project"}
      ]
    ];
BundlePaclet[projName_]:=
  Module[
    {
      buildDir
      },
    buildDir=getProjectBuildDir[projName];
    If[TrueQ@PacletExecute["ValidDirectoryQ", buildDir],
      BundlePaclet[PacletExecute["Paclet", buildDir]]
      ]
    ];
BundlePaclet[nb_NotebookObject, ploc_:Automatic]:=
  Module[
    {
      proj=getNBProjectName[nb, ploc]
      },
    BundlePaclet[proj]
    ]


(* ::Subsubsection::Closed:: *)
(*getPacletDocsTypePath*)



getPacletDocsTypePath[proj_, type_]:=
  Lookup[
      <|
        "symbol"->FileNameJoin@{"ReferencePages", "Symbols"}, 
        "Symbol"->FileNameJoin@{"ReferencePages", "Symbols"}
        |>, 
      type,
      If[StringQ@type,
        Replace[
          (ToUpperCase[StringTake[#, {1}]]<>ToLowerCase@StringDrop[#, 1])&@ type<>"s", 
          s:Except["Guides"|"Tutorials"]:>
            FileNameJoin@{"ReferencePages", s}
          ],
        FileNameJoin@{"ReferencePages", "Symbols"}
        ]
      ]


(* ::Subsubsection::Closed:: *)
(*getPacletDocsLangPath*)



getPacletDocsLangPath[proj_, lang_]:=
  lang


(* ::Subsubsection::Closed:: *)
(*getPacletDocsExt*)



getPacletDocsExt[proj_, ext_]:=
  ext


(* ::Subsubsection::Closed:: *)
(*getPacletSaveLocation*)



(* ::Subsubsubsection::Closed:: *)
(*Older*)



getPacletSaveLocation1[loc_String, lang_, type_]:=
  FileNameJoin@{
    loc, 
    "Documentation", 
    lang, 
    Lookup[
      <|
        "symbol"->FileNameJoin@{"ReferencePages", "Symbols"}, 
        "Symbol"->FileNameJoin@{"ReferencePages", "Symbols"}
        |>, 
      type,
      If[StringQ@type,
        Replace[
          (ToUpperCase[StringTake[#, {1}]]<>ToLowerCase@StringDrop[#, 1])&@ type<>"s", 
          s:Except["Guides"|"Tutorials"]:>
            FileNameJoin@{"ReferencePages", s}
          ],
        FileNameJoin@{"ReferencePages", "Symbols"}
        ]
      ]
    };
getPacletSaveLocation1[pac_PacletManager`Paclet, lang_, type_]:=
  getPacletSaveLocation1[pac["Location"], lang, type];


(* ::Subsubsubsection::Closed:: *)
(*Newer*)



getPacletSaveLocation[projName_String, lang_, type_]:=
  FileNameJoin@Flatten@{
    getProjectBuildDir[projName], 
    getPacletDocsExt[projName, "Documentation"], 
    getPacletDocsLangPath[projName, lang], 
    getPacletDocsTypePath[projName, type]
    };


(* ::Subsubsection::Closed:: *)
(*DocsSaveDirectory*)



DocsSaveDirectory[projName_String, lang_, type_]:=
  getPacletSaveLocation[projName, lang, type]


(* ::Subsubsection::Closed:: *)
(*getPacletSaveFileName*)



getPacletSaveFileName[projName_, baseLang_, type_, baseTitle_]:=
  Module[
    {
      lang=baseLang,
      baseDir,
      title=baseTitle
      },
    lang=Lookup[<|"en"->"English"|>, lang, $Language];
    baseDir=getPacletSaveLocation[projName, lang, type];
    Quiet@CreateDirectory[baseDir, CreateIntermediateDirectories->True];
    If[!StringQ@title, title="Symbol"];
    FileNameJoin@{baseDir, StringTrim[title, ".nb"]<>".nb" }
    ]


getPacletSaveFileName[projName_, nb_]:=
  Module[
    {
      lang,
      type,
      title
      },
    lang=getMeta[nb, "language"];
    type=getMeta[nb, "type"];
    title=getMeta[nb, "label"];
    getPacletSaveFileName[projName, lang, type, title]
    ];


getPacletSaveFileName[nb_]:=
  getPacletSaveFileName[
    getNBProjectName[nb],
    nb
    ];


(* ::Subsubsection::Closed:: *)
(*getSiteTypeExt*)



getSiteTypeExt[proj_, type_]:=
  StringTrim[
    Lookup[<|"symbol"->"ref", "Symbol"->"ref"|>, type,
      If[StringQ@type,
        (*(ToUpperCase[StringTake[#, {1}]]<>StringDrop[#, 1])&@*)
          ToLowerCase@ type, 
        "ref"
        ]
      ],
    "s"~~EndOfString
    ]


(* ::Subsubsection::Closed:: *)
(*getSiteContentExt*)



getSiteContentExt[proj_, ext_]:=
  If[StringQ@ext, ToLowerCase@ext, ext];


(* ::Subsubsection::Closed:: *)
(*getSiteSaveLocation*)



(* ::Subsubsubsection::Closed:: *)
(*Older*)



getSiteSaveLocation1[loc_, type_]:=
  FileNameJoin@{
    docsSiteLoc@loc, 
    "content",
    StringTrim[
      Lookup[<|"symbol"->"ref", "Symbol"->"ref"|>, type,
        If[StringQ@type,
          (ToUpperCase[StringTake[#, {1}]]<>StringDrop[#, 1])&@ type, 
          "ref"
          ]
        ],
      "s"~~EndOfString
      ]
    };


(* ::Subsubsubsection::Closed:: *)
(*Newer*)



getSiteSaveLocation[projName_, type_]:=
  FileNameJoin@Flatten@{
    docsSiteLoc@projName, 
    getSiteContentExt[projName, "content"],
    getSiteTypeExt[projName, type]
    };


(* ::Subsubsection::Closed:: *)
(*SiteSaveDirectory*)



SiteSaveDirectory[projName_String, lang_, type_]:=
  getSiteSaveLocation[projName, type]


(* ::Subsubsection::Closed:: *)
(*getProjectSaveLocation*)



getProjectSaveLocation[projName_, type_]:=
  FileNameJoin@Flatten@{
    docsProjLoc@projName, 
    getSiteContentExt[Automatic, "content"],
    getSiteTypeExt[Automatic, type]
    };


(* ::Subsubsection::Closed:: *)
(*ProjectSaveDirectory*)



ProjectSaveDirectory[projName_String, type_]:=
  getProjectSaveLocation[projName, type]


(* ::Subsubsection::Closed:: *)
(*getSiteSaveFileName*)



(* ::Subsubsubsection::Closed:: *)
(*older*)



getSiteSaveFileName1[pac_, nb_]:=
  Module[
    {
      cont,
      lang,
      type,
      baseDir,
      title,
      pi
      },
    cont=getMeta[nb, "context"];
    lang=getMeta[nb, "language"];
    If[cont===Automatic,
      pi=PacletManager`PacletInformation[pac];
      setMeta[nb, "context",
        First["Context"/.Append[pi, "Context"->{Lookup[pi, "Name"]<>"`"}]]
        ]
      ];
    type=getMeta[nb, "type"];
    InitializeDocsSite[pac];
    baseDir=getSiteSaveLocation[pac, type];
    title=getNbData[nb, {"Metadata", "label"}];
    If[!StringQ@title, title="Symbol"];
    Quiet@CreateDirectory[baseDir, CreateIntermediateDirectories->True];
    FileNameJoin@{baseDir,StringTrim[title, ".nb"]<>".nb" }
    ];


(* ::Subsubsubsection::Closed:: *)
(*newer*)



getSiteSaveFileName[projName_, baseTitle_, baseType_]:=
  Module[
    {
      cont,
      lang,
      type=baseType,
      baseDir,
      title=baseTitle,
      pi,
      projDir,
      pac
      },
    InitializeDocsSite[projName];
    baseDir=getSiteSaveLocation[projName, type];
    If[!StringQ@title, title="Symbol"];
    Quiet@CreateDirectory[baseDir, CreateIntermediateDirectories->True];
    FileNameJoin@{baseDir, StringTrim[title, ".nb"]<>".nb" }
    ];
getSiteSaveFileName[projName_, nb_]:=
  Module[
    {
      title=getMeta[nb, "label"],
      type=getMeta[nb, "type"]
      },
    If[!StringQ@title, title="Symbol"(* this should be changed up... *)];
    getSiteSaveFileName[projName, title, type]
    ];
getSiteSaveFileName[nb_]:=
  getSiteSaveFileName[getNBProjectName[nb], nb];


(* ::Subsubsection::Closed:: *)
(*getProjectSaveFileName*)



getProjectSaveFileName[projName_, baseTitle_, baseType_]:=
  Module[
    {
      cont,
      lang,
      type=baseType,
      baseDir,
      title=baseTitle,
      pi,
      projDir,
      pac
      },
    Block[{docsSiteLoc=docsProjLoc},
      InitializeDocsSite[projName]
      ];
    baseDir=getProjectSaveLocation[projName, type];
    If[!StringQ@title, title="Symbol"];
    Quiet@CreateDirectory[baseDir, CreateIntermediateDirectories->True];
    FileNameJoin@{baseDir, StringTrim[title, ".nb"]<>".nb" }
    ];
getProjectSaveFileName[projName_, nb_]:=
  Module[
    {
      title=getMeta[nb, "label"],
      type=getMeta[nb, "type"]
      },
    If[!StringQ@title, title="Symbol"(* this should be changed up... *)];
    getProjectSaveFileName[projName, title, type]
    ];
getProjectSaveFileName[nb_]:=
  getProjectSaveFileName[getNBProjectName[nb], nb];


(* ::Subsubsection::Closed:: *)
(*CreateDocumentationPaclet*)



CreateDocumentationPaclet[rootDir_, contexts_]:=
  Module[
    {
      targDir,
      cleanName,
      conts=Flatten@{contexts}
      },
    cleanName=
      "Documentation_"<>StringDelete[conts[[1]], "`"];
    targDir=FileNameJoin@{rootDir, cleanName};
    If[!DirectoryQ@targDir,
      CreateDirectory[targDir, CreateIntermediateDirectories->True]
      ];
    If[!PacletExecute["ValidDirectoryQ", targDir],
      PacletExecute["GeneratePacletInfo", 
        targDir, 
        "Name"->cleanName,
        "Version"->"0.0.0"
        ]
      ];
    targDir
    ]


(* ::Subsection:: *)
(*Workbench*)



(* ::Subsubsection::Closed:: *)
(*WorkbenchTemplateData*)



(* ::Subsubsubsection::Closed:: *)
(*extractMetadata*)



extractMetadata[cellData_, cellLabels_]:=
  With[
    {
      basics=
        AssociationThread[
          cellLabels/.{
            "Entity Type"->"Type",
            "Paclet Name"->"Paclet"
            },
          cellData[[All, 1]]
          ]
      },
    Normal@
      Merge[
        {
          DeleteCases[
            basics,
            "XXXX"|Except[_String]
            ],
          "Label"->URLParse[basics["URI"], "Path"][[-1]]
          },
        First
        ]//DocMetadata
    ]


(* ::Subsubsubsection::Closed:: *)
(*styleConvert*)



styleConvert//Clear;
fallbackStyleConversions=
  Dispatch@{
      "TI":>Sequence@@{"InlineFormula", FontSlant->Italic},
      "ModInfo"->"Text",
      "Notes"->"Item",
      "SeeAlso"->"Text",
      "ObjectName"->"Section",
      "GuideTitle"->"Section",
      "MoreAbout"->"Text",
      "Tutorials"->"Text",
      "GuideAbstract"->"Text",
      "InlineGuideFunction":>Sequence@@{"InlineFormula", "Input"},
      "InlineFormula":>Sequence@@{"InlineFormula", "Input"},
      "DisplayMath":>Sequence@@{"DisplayFormulaNumbered", TextAlignment->Center},
      _String?(StringStartsQ["Related"])->"Text"
      };
styleConvert[s_String]:=
  Sequence@@Flatten@List@Catch[
        Scan[
          If[StringEndsQ[s, #], Throw@#]&,
          {
            "Text",
            "Link"
            }
          ];
        KeyValueMap[
          If[StringEndsQ[s, #], Throw[#2]]&,
          Join[
            <|
              "Listing"->"Text",
              "TableMod":>{"Input", "DetailsGrid"}
              |>,
            AssociationThread[
              NestList[StringReplace["S"->"Subs"], "Section", 5],
              NestList[StringReplace["S"->"Subs"], "Subsection", 5]
              ]
            ]
          ];
        Replace[s, fallbackStyleConversions]
        ];
styleConvert[e___]:=e


(* ::Subsubsubsection::Closed:: *)
(*cellDataConvert*)



convertUsageData//Clear;


convertUsageData[TextData[l_List]]:=
  Replace[
    Join@@@Partition[
      SplitBy[
        Flatten@
          Reap[
            Replace[l,
              {
                Cell[a_, "InlineFormula", o___]:>
                  Sow@Cell[a,"Code", "UsageInput", o],
                e:Except[_Cell]:>Sow[e],
                _->Nothing
                },
              1
              ]
            ][[2]],
        Head[#]===Cell&
        ],
      2
      ],
    {
      {c_Cell, s___}:>
        ReplaceAll[
          {
            c, 
            Cell[TextData[{s}], "Text","UsageText"]
            },
          {
            r_String:>StringDelete[r, "\[LineSeparator]"|"\n"],
            StyleBox[a_, style_String, b___]:>
              RuleCondition[StyleBox[a, styleConvert[style], b], True]
            }
          ]
      },
    1
    ];


cleanUpInterpBoxes[InterpretationBox[a_, b_]]:=
  a;


cleanUpInterpBoxes[InterpretationBox[GridBox[{{a_, ___},___}, ___], b_]]:=
  a;


cellDataConvert//Clear
cellDataConvert[Cell[data_, "Usage", o___]]:=
  Sequence@@{
    Cell[
      CellGroupData[Flatten@{
            Cell["", "UsageSection"],
            convertUsageData[data],
            Cell["", "UsageSectionFooter"]
            }]
      ],
    Cell["Details", "Subsection"]
    };
cellDataConvert[Cell[data_, "ExampleDelimiter", o___]]:=
  cellDataConvert@Cell["", "GuideDelimiter"]
cellDataConvert[Cell[data_, _String?(StringEndsQ["Delimiter"]), o___]]:=
  Cell["", "PageBreak", 
    PageBreakWithin->False,
    PageBreakBelow->False, 
    PageBreakAbove->False
    ];
cellDataConvert[Cell[data_, k:"DisplayMath", o___]]:=
  Cell[
    FirstCase[data, f_FormBox:>BoxData[f], data, Infinity], 
    styleConvert[k],
    o
    ]
cellDataConvert[Cell[data_, s_String?(StringStartsQ["Example"]), o___]]:=
  Cell[
    data/.i_InterpretationBox:>cleanUpInterpBoxes[i],
    styleConvert[s],
    o
    ];
cellDataConvert[Cell["XXXX", ___]]:=
  Nothing;
cellDataConvert[Cell[data_, style_, o___]]:=
  Cell[data/.{
      c_Cell:>cellDataConvert[c],
      StyleBox[a_, s_String, b___]:>
        RuleCondition[StyleBox[a, styleConvert[s], b], True]
      },
     styleConvert[style], 
    o
    ];
cellDataConvert~SetAttributes~Listable;


(* ::Subsubsubsection::Closed:: *)
(*getStyleType*)



getStyleType[sname_]:=
  Catch[
    If[StringStartsQ[sname, "Related"],
      Throw[StringTrim[sname, "Section"]]
      ];
    KeyValueMap[
      If[StringEndsQ[sname, #],Throw[#2]]&,
      <|
        "Title"|"ObjectName"->"Body",
        "FunctionsSection"->"Body",
        "ExampleSection"->"Examples",
        "ExamplesSection"->"Examples",
        "MoreAboutSection"->"RelatedGuides",
        "TutorialsSection"->"RelatedTutorials",
        "SeeAlsoSection"->"RelatedFunctions"
        |>
      ];
    None
    ]


(* ::Subsubsubsection::Closed:: *)
(*processCellSections*)



processCellSections[data_]:=
  Replace[
    DeleteCases[
      ReplaceAll[
        cellDataConvert@Flatten@data,
        c:Cell[
          a_, 
          s:Alternatives@@NestList[StringReplace["S"->"Subs"], "Section", 5], 
          b___
          ]:>
          Quiet@Cell[
              First@FrontEndExecute@ExportPacket[c, "PlainText"], 
              s, 
              b
              ]
        ],
      Cell["XXXX", ___],
      Infinity
      ],
    {_Cell}->Nothing
    ]


(* ::Subsubsubsection::Closed:: *)
(*processBlankableSections*)



processBlankableSections[data_]:=
  data//.{
    {a___, Cell[_, "Subsection", ___], b:Cell[_, "Subsection", ___], c___}:>
      {a, b, c},
    {a___, Cell[_, "Subsection", ___]}:>{a}
    }


(* ::Subsubsubsection::Closed:: *)
(*extractNotebookData*)



extractNotebookData[nb_NotebookObject]:=
  Module[
    {
      cells=Cells[nb],
      cellData,
      cellLabels,
      meta,
      ctag,
      nbData
      },
    cellData=NotebookRead@cells;
    cellLabels=CurrentValue[cells, CellLabel];
    meta=
      extractMetadata[Pick[cellData, #], Pick[cellLabels, #]]&@
        Map[StringQ, cellLabels];
    ctag="Preamble";
    nbData=
      GroupBy[
        Reap[
          Do[
            Replace[
              getStyleType@cell[[2]], 
              s_String:>Set[ctag, s]
              ];
            Sow[cell, ctag],
            {cell, cellData}
            ],
          _,
          Rule
          ][[2]],
        First->Last,
        processCellSections
        ];
    AssociationMap[
      #[[1]]->
        If[StringStartsQ[#[[1]], "Related"|"Examples"],
          processBlankableSections[#[[2]]],
          #[[2]]
          ]&,
      PrependTo[nbData, "Metadata"->meta]
      ]
    ]


(* ::Subsubsubsection::Closed:: *)
(*WorkbenchTemplateData*)



WorkbenchTemplateData[nb_NotebookObject]:=
  extractNotebookData[nb];
WorkbenchTemplateData[f_String?FileExistsQ]:=
  Module[{nb},
    Internal`WithLocalSettings[
      nb = NotebookOpen[f, Visible->False],
      WorkbenchTemplateData[nb],
      NotebookClose[nb]
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*FromWorkbenchTemplate*)



(* ::Subsubsubsection::Closed:: *)
(*rebuildNotebook*)



rebuildNotebook[
  data_Association,
  projectName:_String|Automatic:Automatic,
  projectDirectory:_String|_FrontEnd`FileName|Automatic:Automatic
  ]:=
  Module[
    {
      meta=Association@data["Metadata"],
      projName,
      projDir
      },
    projName=
      Replace[projectName,
        Automatic:>StringSplit[meta["context"], "`"][[1]]
        ];
    projDir=
      Replace[projectDirectory,
        Automatic:>
          Replace[
            PacletManager`PacletFind[projName],
            {
              p:{__}:>
                SelectFirst[#["Location"]&/@p,
                  Not@*StringStartsQ[PacletManager`$UserBasePacletsDirectory]
                  ],
              _:>
                BTools`Paclets`AppExecute["Path", projName]
              }
            ]
        ];
    Notebook[
      Flatten@{
          Cell[projName<>" "<>Lookup[meta, "type", "Symbol"],"TitleBar"],
          data["Body"],
          Lookup[data,
            {
              "Examples",
              "RelatedFunctions",
              "RelatedGuides",
              "RelatedLinks",
              "RelatedDemonstrations"
              }, 
            Nothing
            ],
          Values@
            KeyDrop[
              KeySelect[data, StringStartsQ["Related"]],
              {
                "RelatedFunctions", "RelatedGuides",
                "RelatedLinks","RelatedDemonstrations"
                }
              ]
          },
      TaggingRules->{
          "Metadata"->Normal@meta,
          "ColorType"->Lookup[meta, "type", "Symbol"]<>"Color",
          "SimpleDocs"->{
              "Project"->{
                  "Name"->projName,
                  "Directory"->projDir
                  }
              }
          },
      ScreenStyleEnvironment->"Editing",
      StyleDefinitions->
        FrontEnd`FileName[{"SimpleDocs"}, "SimpleDocs.nb"]
      ]
    ];
rebuildNotebook[
nb_NotebookObject,
projectName:_String|Automatic:Automatic,
projectDirectory:_String|_FrontEnd`FileName|Automatic:Automatic
]:=
rebuildNotebook[
extractNotebookData@nb,
projectName,
projectDirectory
];
rebuildNotebook[
f_String?FileExistsQ,
projectName:_String|Automatic:Automatic,
projectDirectory:_String|_FrontEnd`FileName|Automatic:Automatic
]:=
Module[{doopdoop},
Internal`WithLocalSettings[
doopdoop=NotebookOpen[f, Visible->False],
rebuildNotebook[doopdoop, projectName, projectDirectory],
NotebookClose[doopdoop]
]
]


(* ::Subsubsubsection::Closed:: *)
(*buildSimpleStyledDocs*)



buildSimpleStyledDocs[a__]:=
  Module[{nb},
    Replace[
      rebuildNotebook[a],
      {
        n_Notebook:>
          Internal`WithLocalSettings[
            nb=CreateDocument[n, Visible->False],
            SimpleDocs@"SaveToProject"[nb],
            NotebookClose[nb]
            ],
        _->$Failed
        }
      ]
    ];


(* ::Subsubsubsection::Closed:: *)
(*FromWorkbenchTemplate*)



Options[FromWorkbenchTemplate]=
  {
    "Name"->Automatic,
    "Directory"->Automatic
    };
FromWorkbenchTemplate[obj_,
  ops:OptionsPattern[]
  ]:=
  buildSimpleStyledDocs[
    obj,
    OptionValue["Name"],
    OptionValue["Directory"]
    ];


End[];



