(* ::Package:: *)

(* Autogenerated Package *)

CreateMessagePopup::usage="Attaches a Message popup to a notebook";
MessagePopupPanel::usage="A panel for a Message popup";


IDECreateMessage::usage=""


Begin["`Private`"];


(* ::Subsection:: *)
(*CreateMessagePopup*)



(* ::Subsubsection::Closed:: *)
(*MessagePopupPanel*)



MessagePopupPanel[expression_, ops:OptionsPattern[]]:=
  Panel[
    Grid[
      {
        {
          Pane[expression], 
          RawBoxes@ButtonBox["", BaseStyle->"MessagePopupClose"]
          }
        },
      GridBoxItemSize->Inherited
      ],
    ops,
    BaseStyle->"MessagePopup"
    ]


(* ::Subsubsection::Closed:: *)
(*CreateMessagePopup*)



attachables=
  _NotebookObject|_FrontEnd`EvaluationNotebook|_FrontEnd`InputNotebook|
  _FrontEnd`SelectedNotebook|_FrontEnd`ParentNotebook|_FrontEnd`ButtonNotebook|
  _CellObject|_FrontEnd`EvaluationCell|_FrontEnd`ParentCell|_FrontEnd`IndexedCell|
  _BoxObject|_FrontEnd`EvaluationBox|_FrontEnd`ParentBox;


CreateMessagePopup//Clear
CreateMessagePopup[
  nb:attachables, 
  expression_, 
  position:{_Integer|_Scaled, _Integer|_Scaled}:{-15, -15},
  align:{Left|Center|Right, Bottom|Center|Top}:{Right, Bottom},
  anchor:{Left|Center|Right, Bottom|Center|Top}:{Right, Bottom},
  ops:OptionsPattern[]
  ]:=
  FEAttachCell[
    nb,
    Cell[
      BoxData@ToBoxes@
        MessagePopupPanel[expression, FilterRules[{ops}, Options[Panel]]],
      "MessagePopupCell",
      Sequence@@
        FilterRules[
          FilterRules[{ops}, Options[Cell]],
          Except[Alternatives@@Keys[Options[Panel]]]
          ]
      ],
    Offset[position, 0],
    align,
    anchor,
    {"OutsideMouseClick"}
    ];
CreateMessagePopup[
  expression:Except[attachables], 
  position:{_Integer|_Scaled, _Integer|_Scaled}:{-15, -15},
  align:{Left|Center|Right, Bottom|Center|Top}:{Right, Bottom},
  anchor:{Left|Center|Right, Bottom|Center|Top}:{Right, Bottom},
  ops:OptionsPattern[]
  ]:=
  CreateMessagePopup[
    $CurrentIDENotebook,
    expression,
    position,
    align,
    anchor,
    ops
    ]


(* ::Subsection:: *)
(*IDECreateMessage*)



IDECreateMessage[nb_NotebookObject, expr_, args___]:=
  CreateMessagePopup[nb, expr, args];
IDECreateMessage[ide_IDENotebookObject, expr_, args___]:=
  CreateMessagePopup[ide["Notebook"], expr, args];


End[];



