(* ::Package:: *)

(* Autogenerated Package *)

BugObject::usage=
  "An object representing a bug internally";
BugsToDataset::usage=
  "Converts a set of bugs to a Dataset for ease of searching";
DatasetToBugs::usage=
  "Converts a dataset of a list of bugs objects";


Begin["`Private`"];


(* ::Subsection:: *)
(*Bugs Objects*)



(* ::Subsubsection::Closed:: *)
(*BugsToDataset*)



BugsToDataset[b:{__BugObject}]:=
  Dataset@KeyDrop[Map[Normal, b], "Version"];
BugsToDataset[nb:_Notebook|_NotebookObject]:=
  BugsToDataset@BugsNotebookToBugs[nb]


(* ::Subsubsection::Closed:: *)
(*DatasetToBugs*)



DatasetToBugs[d_Dataset]:=
  BugObject/@Normal[d];


(* ::Subsection:: *)
(*Bugs Objects*)



(* ::Subsubsection::Closed:: *)
(*$BugObjectKeys*)



$BugObjectKeys=
  Prepend["Tag"]@
    Keys@Options@BugsNotebookCell;


(* ::Subsubsection::Closed:: *)
(*ConstructBugObject*)



ConstructBugObject//Clear
ConstructBugObject[a_Association]:=
  Merge[
    {
      a,
      AssociationThread[$BugObjectKeys->None]
      },
    First
    ]


(* ::Subsubsection::Closed:: *)
(*Register*)



RegisterInterface[
  BugObject,
  $BugObjectKeys,
  "Constructor"->ConstructBugObject,
  "Validator"->BugObjectQ,
  "Formatted"->False
  ]


(* ::Subsubsection::Closed:: *)
(*Format*)



MakeBoxes[b_BugObject?BugObjectQ, form_]:=
  With[{a=Normal[b]},
    BoxForm`ArrangeSummaryBox[
      "BugObject",
      b,
      Pane[
        RawBoxes@
          DynamicBox[
            FEPrivate`ImportImage@
              FrontEnd`FileName[{"BugTracker"}, "BeetleIcon.png"]
            ],
        {28, 28},
        ImageSizeAction->"ShrinkToFit"
        ],
      {
        BoxForm`MakeSummaryItem[{"Tag: ", Lookup[a, "Tag", "Untagged"]}, form]
        },
      KeyValueMap[
        BoxForm`MakeSummaryItem[{Row@{#, ": "}, #2}, form]&,
        KeyDrop[a, "Tag"]
        ],
      form
      ]
  ]


End[];



