(* ::Package:: *)

(* Autogenerated Package *)

BugsNotebookAddDataDialog::usage="Opens a dialog for getting bug data";
BugsNotebookSearchBar::usage="Search bar for a bugs notebook";
BugsNotebookWriteViewCell::usage="Writes a cell for viewer stuff";
BugsNotebookViewDatasetButton::usage="";
BugsNotebookViewListButton::usage="";
BugsCellToBug::usage="Converts a cell to a bug";


Begin["`Private`"];


(* ::Subsection:: *)
(*Stylesheet Stuff*)



(* ::Subsubsection::Closed:: *)
(*BugsNotebookAddDialog*)



bugDialogEntry//Clear


bugDialogEntry[sym_, key_, ops:OptionsPattern[]]:=
  Sequence[
    Row@{Spacer[10], Style[key, "Subsection"]},
    Row@{
      Spacer[25],
      InputField[
        Dynamic[sym[key]],
        String,
        FieldHint->ToLowerCase@key,
        BoxID->ToLowerCase@key,
        ops
        ]
      }
    ];
bugDialogEntry~SetAttributes~HoldFirst


BugsNotebookAddDataDialog//Clear
BugsNotebookAddDataDialog[ops:OptionsPattern[]]:=
  DialogInput[
    {bugData=<|"Tag"->"", "Title"->"", "Package"->"", "Keywords"->""|>},
    Pane[
      EventHandler[
        Column@{
          Style["Bug info:", "Section"],
          Spacer[{5, 10}],
          bugDialogEntry[bugData, "Tag",
            FieldSize->50],
          bugDialogEntry[bugData, "Title",
            FieldSize->50],
          bugDialogEntry[bugData, "Package",
            FieldSize->50],
          bugDialogEntry[bugData, "Keywords",
            FieldSize->50
            ],
          bugDialogEntry[bugData, "Description",
            FieldSize->{50, 6}
            ]
          },
        {
          "ReturnKeyDown":>
            DialogReturn@
              If[StringLength@bugData["Tag"]>0, bugData, $Canceled],
          "EscapeKeyDown":>
            DialogReturn[$Canceled]
          }
        ],
      {480, 425},
      Alignment->Center
      ],
    ops,
    NotebookDynamicExpression:>
      Refresh[
        FrontEnd`MoveCursorToInputField[EvaluationNotebook[], "tag"],
        None
        ]
    ]


(* ::Subsubsection::Closed:: *)
(*BugsNotebookSearchBar*)



BugsNotebookSearchBar//Clear
BugsNotebookSearchBar[ops:OptionsPattern[]]:=
  Row@{
    Panel[
      EventHandler[
        InputField[
          Dynamic@
            CurrentValue[EvaluationNotebook[], 
              {TaggingRules, "Bugs", "SearchInterface", "SearchText"},
              ""
              ],
          String,
          ops,
          Appearance->"Frameless"
          ],
        {
          "ReturnKeyDown":>
            (
              Replace[
                BugsNotebookLocate[
                  EvaluationNotebook[],
                  CurrentValue[EvaluationNotebook[], 
                    {TaggingRules, "Bugs", "SearchInterface", "SearchText"}
                    ]
                  ],
                $Failed:>Beep[]
                ];
              CurrentValue[EvaluationNotebook[], 
                {TaggingRules, "Bugs", "SearchInterface", "SearchText"}
                ]=""
              )
          }
        ],
      FrameMargins->{{5, 5}, {5, 5}},
      Appearance->
        {
          "Hover"->
            FrontEnd`FileName[{"BugTracker"}, "SearchBackground-Hover.png"]
          }
      ],
  Spacer[5],
  Button[
    "",
    (
      Replace[
        BugsNotebookLocate[
          EvaluationNotebook[],
          CurrentValue[EvaluationNotebook[], 
            {TaggingRules, "Bugs", "SearchInterface", "SearchText"}
            ]
          ],
        $Failed:>Beep[]
        ];
      CurrentValue[EvaluationNotebook[], 
        {TaggingRules, "Bugs", "SearchInterface", "SearchText"}
        ]=""
      ),
    Appearance->
      {
        "Default"->FrontEnd`FileName[{"BugTracker"}, "Search-Default.png"],
        "Hover"->FrontEnd`FileName[{"BugTracker"}, "Search-Hover.png"],
        "Pressed"->FrontEnd`FileName[{"BugTracker"}, "Search-Pressed.png"]
        },
    ImageSize->{16, 16}
    ]
  }


(* ::Subsubsection::Closed:: *)
(*BugsNotebookView*Button*)



(* ::Subsubsubsection::Closed:: *)
(*BugsNotebookWriteViewCell*)



BugsNotebookWriteViewCell[data_]:=
  With[
    {
      cell=
        Cell[BoxData@ToBoxes@data, "Output",
          CellTags->{"Bugs", "BugsView"}
          ]
      },
    Replace[
      Cells[FrontEnd`EvaluationNotebook[], CellTags->"BugsView"],
      {
        {c_, ___}:>
          NotebookWrite[c, cell],
        _:>
          Internal`WithLocalSettings[
            FrontEndExecute@
              FrontEnd`NotebookSuspendScreenUpdates@FrontEnd`EvaluationNotebook[],
            FrontEndExecute@
              Flatten@{
                FrontEnd`SelectionMove[FrontEnd`EvaluationCell[], After, Cell],
                ConstantArray[
                  FrontEnd`SelectionMove[FrontEnd`EvaluationNotebook[], After, Cell],
                  5
                  ]
                };
            NotebookWrite[EvaluationNotebook[], cell],
            FrontEndExecute@
              FrontEnd`NotebookResumeScreenUpdates@FrontEnd`EvaluationNotebook[]
            ]
        }
      ]
    ]


(* ::Subsubsubsection::Closed:: *)
(*BugsNotebookViewListButton*)



BugsNotebookViewListButton[]:=
  Button["View List", 
    Needs["BugTracker`"];
    BugsNotebookWriteViewCell@
      BugsNotebookToBugs@EvaluationNotebook[],
    Appearance->
      {
        "Default"->
          FrontEnd`FileName[{"BugTracker"}, "ButtonAppearanceLeft-Default.png"],
        "Hover"->
          FrontEnd`FileName[{"BugTracker"}, "ButtonAppearanceLeft-Hover.png"],
        "Pressed"->
          FrontEnd`FileName[{"BugTracker"}, "ButtonAppearanceLeft-Pressed.png"]
        },
    FrameMargins->{{10, 10}, {5, 5}}
    ]


(* ::Subsubsubsection::Closed:: *)
(*BugsNotebookViewDatasetButton*)



BugsNotebookViewDatasetButton[]:=
  Button["View Dataset", 
    Needs["BugTracker`"];
    BugsNotebookWriteViewCell@
      BugsToDataset@BugsNotebookToBugs@EvaluationNotebook[],
    Appearance->
      {
        "Default"->
          FrontEnd`FileName[{"BugTracker"}, "ButtonAppearanceRight-Default.png"],
        "Hover"->
          FrontEnd`FileName[{"BugTracker"}, "ButtonAppearanceRight-Hover.png"],
        "Pressed"->
          FrontEnd`FileName[{"BugTracker"}, "ButtonAppearanceRight-Pressed.png"]
        },
    FrameMargins->{{10, 10}, {5, 5}}
    ]


End[];



