(* ::Package:: *)

(* Autogenerated Package *)

FindBugsNotebook::usage=
  "Find the bugs notebook for a project";
NewBugsNotebook::usage=
  "Creates a new bugs notebook for a project";
BugsNotebookOpen::usage=
  "Opens a BugsTracker notebook for a project";


Begin["`Private`"];


$BugsNotebookExtensions=
  {
    {"project", "bugs"},
    {"Testing", "Bugs"},
    {"Private", "Bugs"},
    {"Bugs"},
    {}
    }


(* ::Subsubsection::Closed:: *)
(*NewBugsNotebook*)



NewBugsNotebook[
  dir:(_String|_File)?DirectoryQ, 
  name:_?StringQ:"BugTracker.nb"
  ]:=
  BugsNotebookOpen@
    Export[
      FileNameJoin@{dir, StringTrim[name, ".nb", IgnoreCase->True]<>".nb"},
      BugsNotebook[{}]
      ];
NewBugsNotebook[
  p_PacletManager`Paclet,
  name:_?StringQ:"BugTracker.nb"
  ]:=
  With[{targ=FileNameJoin@{p["Location"], "project", "bugs"}},
    Quiet@CreateDirectory[targ, CreateIntermediateDirectories->True];
    NewBugsNotebook[targ, name]
    ];
NewBugsNotebook[
  p_String, 
  name:_?StringQ:"BugTracker.nb"
  ]:=
  With[{pacs=PacletManager`PacletFind[p]},
    NewBugsNotebook[pacs[[1]], name]/;Length@pacs>0
    ]


(* ::Subsubsection::Closed:: *)
(*BugsNotebookOpen*)



ClearAll[BugsNotebookOpen];
Options[BugsNotebookOpen]=
  Options[NotebookOpen]
BugsNotebookOpen[
  nb:(_String|_File)?(FileExistsQ[#]&&!DirectoryQ[#]&),
  ops:OptionsPattern[]
  ]:=
  NotebookOpen[nb, ops,
    StyleDefinitions->PackageFEFile["Private", "BugTracker.nb"]
    ]
BugsNotebookOpen[
  dir:(_String|_File)?DirectoryQ, 
  nbPattern:_?StringPattern`StringPatternQ:"BugTracker.nb",
  ops:OptionsPattern[NotebookOpen]
  ]:=
  Replace[FindBugsNotebook[dir, nbPattern, ops],
    {
      f_String:>
        BugsNotebookOpen[f, ops]
      }
    ]


(* ::Subsubsection::Closed:: *)
(*FindBugsNotebook*)



FindBugsNotebook[
  dir:(_String|_File)?DirectoryQ, 
  nbPattern:_?StringPattern`StringPatternQ:"BugTracker.nb"
  ]:=
  Replace[
    FileNames[
      nbPattern,
      FileNameJoin@Prepend[#, dir]&/@$BugsNotebookExtensions
      ],
    {
      {f_, ___}:>f,
      _->$Failed
      }
    ]


End[];



