(* ::Package:: *)

(* Autogenerated Package *)

IDENotebookObject::usage=
  "The basic representation of a NotebookObject that supports an IDE";


Begin["`Private`"];


RegisterInterface[
  IDENotebookObject,
  {"Project", "NotebookObject"},
  "Constructor"->CreateIDENotebook,
  "MutationFunctions"->{"Keys"}
  ]


End[];



