(* ::Package:: *)

(* Autogenerated Package *)

ProjectObject::usage=
  "The basic representation of a project used by the EasyIDE package";


Begin["`Private`"];


RegisterInterface[
  ProjectObject,
  {"Name", "Root"}
  ]


End[];



